### PR TITLE
fix(common): AnsiOutputStream exceptions don't prevent logging or program execution

### LINKED ISSUE #2004: Shutting down JKube remote dev is crashing
### Describe the bug

Shutting down (Ctrl-C) the remote-dev is crashing. The cluster is not set back to the normal state.

### Eclipse JKube version

1.10.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

1. Follow the https://github.com/marcnuri-demo/jkube-remote-dev#remote-dev-demo-walk-through demo walk-through to the step `Stop the remote-dev by typing Ctrl-c in the terminal where it has been started`
2. Hitting `Ctrl-C`, the exception is raised:
    ```
    [INFO] Server announced support for publickey-hostbound@openssh.com version 0
    [INFO] k8s: Kubernetes Service northwind-db:5432 is now available at local port 5432
    [INFO] k8s: Kubernetes Service rabbit-mq:5672 is now available at local port 15672
    [INFO] k8s: Local port '8080' is now available as a Kubernetes Service at northwind:8080
    ^C[Exception in thread "Thread-2" java.lang.NumberFormatException: For input string: "0m"
    	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    	at java.base/java.lang.Integer.parseInt(Integer.java:668)
    	at java.base/java.lang.Integer.valueOf(Integer.java:999)
    	at org.fusesource.jansi.io.AnsiOutputStream.write(AnsiOutputStream.java:199)
    	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
    	at java.base/java.io.PrintStream.write(PrintStream.java:568)
    	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
    	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
    	at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
    	at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
    	at java.base/java.io.PrintStream.write(PrintStream.java:699)
    	at java.base/java.io.PrintStream.print(PrintStream.java:863)
    	at java.base/java.io.PrintStream.println(PrintStream.java:1031)
    	at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:341)
    	at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:310)
    	at org.slf4j.impl.SimpleLogger.info(SimpleLogger.java:504)
    	at org.apache.maven.cli.logging.Slf4jLogger.info(Slf4jLogger.java:59)
    	at org.apache.maven.monitor.logging.DefaultLog.info(DefaultLog.java:68)
    	at org.eclipse.jkube.kit.common.util.AnsiLogger.info(AnsiLogger.java:98)
    	at org.eclipse.jkube.kit.remotedev.RemoteDevelopmentService.stop(RemoteDevelopmentService.java:56)
    	at org.eclipse.jkube.maven.plugin.mojo.develop.RemoteDevMojo.lambda$executeInternal$0(RemoteDevMojo.java:46)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    ```

### Expected behavior

1. It should stop properly with no errors.
2. It should tell the user how to restore the state manually.

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

### Eclipse JKube Logs

_No response_

### Sample Reproducer Project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manusa**
## Description

Fixes #2004

fix(common):AnsiOutputStream exceptions don't prevent logging or program execution

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java [hunk 1]
```diff
@@ -45,257 +45,260 @@
  * @since 31.03.14
  */
 public class AnsiLogger implements KitLogger {
-    // prefix used for console output
```
Comment (sunix) [inline jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java:48]: It is quite hard to spot the differences with the code format

Comment (manusa) [reply jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java:48]: Yup, I saw that later. The only difference is the usage of the `withFallback` method for logging. This allows to catch **any** exception when using Ansi to log messages.

**Review by sunix — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]
