### PR TITLE
fix : Build ARGS not replaced properly (#1382)

### LINKED ISSUE #1382: Build args not replaced properly
Hi.
I'm trying to build a Docker image from a custom Dockerfile using the version 1.7.0 of the jkube-maven-plugin and I've the following error during the execution of the build goal
```
[ERROR] k8s: Failed to execute the build [Error while trying to build the image: Unable to check image [registry.access.redhat.com/ubi8/openjdk-${JAVA_VERSION}-runtime] : {"message":"no such image: registry.access.redhat.com/ubi8/op
enjdk-${JAVA_VERSION}-runtime: invalid reference format: repository name must be lowercase"} (Bad Request: 400)]
```

Dockerfile
```
ARG JAVA_VERSION=17

FROM registry.access.redhat.com/ubi8/openjdk-${JAVA_VERSION}-runtime
LABEL org.opencontainers.image.authors="cosimo.prete.damiano@gmail.com"

ARG JAR_NAME
ADD target/${JAR_NAME}.jar ./phone-book-backend.jar

ENTRYPOINT ["java", "-jar", "phone-book-backend.jar"]
```

Maven config
```xml
<execution>
                            <id>build-${docker.image-name}-docker-image</id>
                            <phase>package</phase>
                            <goals>
                                <goal>build</goal>
                            </goals>
                            <configuration>
                                <images>
                                    <image>
                                        <name>${docker.qualified-image-name}</name>
                                        <build>
                                            <tags>${project.version}</tags>
                                            <contextDir>${project.basedir}</contextDir>
                                            <assembly>
                                                <name>./</name>
                                            </assembly>
                                            <args>
                                                <JAR_NAME>${project.build.finalName}</JAR_NAME>
                                                <JAVA_VERSION>${java.version}</JAVA_VERSION>
                                            </args>
                                        </build>
                                    </image>
                                </images>
                            </configuration>
                        </execution>
```

Any clue?

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1382  

Port https://github.com/fabric8io/docker-maven-plugin/pull/1490 from
Docker Maven Plugin to JKube in order to fix build ARG resolution issue
while pulling images

I've tested with Dockerfile provided in the issue. This seems to fix the issue reported in #1382 

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java [hunk 1]
```diff
@@ -160,34 +159,29 @@ private static Reader getFileReaderFromDir(File file) {
...
 
-    static String resolveArgValueFromStrContainingArgKey(String argString, Map<String, String> args) {
-        Matcher matcher = argPattern.matcher(argString);
-        if (matcher.matches()) {
-            if (matcher.group(1) != null) {
-                return args.get(matcher.group(1));
-            } else if (matcher.group(2) != null) {
-                return args.get(matcher.group(2));
+    static Set<String> findAllArgs(String imageTagString) {
+        Matcher m = Pattern.compile(ARG_PATTERN_REGEX).matcher(imageTagString);
```
Comment (manusa) [inline jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java:175]: The static Pattern instance was removed and now we're instantiating it for each call.

File: jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java [hunk 2]
```diff
@@ -182,12 +183,8 @@ public void testCustomInterpolation() throws IOException {
     @Test
     public void testMultiStageWithArgs() throws Exception {
         File toTest = copyToTempDir("Dockerfile_multi_stage_with_args");
-        Iterator<String> fromClauses = DockerFileUtil.extractBaseImages(toTest, new Properties(), BuildConfiguration.DEFAULT_FILTER, Collections.emptyMap())
-                .iterator();
-
-        assertEquals("fabric8/s2i-java:latest", fromClauses.next());
-        assertEquals("busybox:latest", fromClauses.next());
-        assertFalse(fromClauses.hasNext());
+        assertThat(DockerFileUtil.extractBaseImages(toTest, new Properties(), BuildConfiguration.DEFAULT_FILTER, Collections.emptyMap()))
```
Comment (manusa) [inline jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java:186]: Could we use a String literal instead of the Buildconfiguration.DEFAULT_FILTER constant here?

File: jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java [hunk 3]
```diff
@@ -261,20 +255,29 @@ private static File getHomeDir() {
     private static void updateMapWithArgValue(Map<String, String> result, Map<String, String> args, String argString) {
         if (argString.contains("=") || argString.contains(":")) {
             String[] argStringParts = argString.split("[=:]");
-            String argStringValue = argString.substring(argStringParts[0].length() + 1);
+            String argStringKey = argStringParts[0];
+            String argStringValue = determineFinalArgValue(argString, argStringParts, args);
             if (argStringValue.startsWith("\"") || argStringValue.startsWith("'")) {
                 // Replaces surrounding quotes
-                argStringValue = trimSurroundingQuotes(argStringValue);
+                argStringValue = argStringValue.replaceAll("[\"']", "");
```
Comment (manusa) [inline jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java:262]: This is not OK, you haven't ported the correct regex. It will fail for strings such as `"hello 'you'"` or `'hello "you"'`
Please, be very careful when dealing with regular expressions, they are the nightmare of every developer.
