### PR TITLE
fix(jkube-kit-config-image): Made digest algorithm check dynamic for ImageName

### LINKED ISSUE #2540: ImageName fails to process image with digest when digest algorithm other than `sha256`
### Describe the bug

ImageName is unable to process image when used with a digest when digest algorithm is not `sha256`.

This is happening because we're doing a hardcoded check for digest algorithm here:
https://github.com/eclipse/jkube/blob/b47fa4a9ab9a839bd4f8a093b4b0a4d8e9c88e9f/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L82

We should rather rely on a regexp like done by [Docker Distribution](https://github.com/distribution/reference) in[ reference.go](https://github.com/distribution/reference/blob/main/reference.go#L289)

Digest regexp pattern can be seen in [regexp.go](https://github.com/distribution/reference/blob/8507c7fcf0da9f570540c958ea7b972c30eeaeca/regexp.go#L81)
```golang
digestPat = `[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,}`
```

According to [OpenContainers Image Spec](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#registered-algorithms) it can be one of two values:
- [SHA-256](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-256)
- [SHA-512](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-512)

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

Try to invoke `new ImageName("xn--7o8h.com/myimage:xn--7o8h.com@sha512:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")` and you'll get exception

### Expected behavior

ImageName doesn't throw exception when digest algorithm is other than SHA256

### PR DESCRIPTION
**Pull request by ShantKhatri**
## Description

Fixes #2540 
Removed hard code check for digest algorithm check in ImageName and replaced it with the dynamic approach which is supportive for if digest algorithm is other than sha256.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2645 (_2024-02-09T08:39:50Z_)

:gear: [JKube E2E Tests (7841545380)](https://github.com/jkubeio/ci/actions/runs/7841545380) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2645)](https://github.com/jkubeio/ci/actions/runs/7841545380/job/21398088014)

**Comment by rohanKanojia** [comment]
@ShantKhatri : Could you please uncomment this line?

https://github.com/eclipse/jkube/blob/604eb9c8c74a77f963bf1fddf7877bef01f53d82/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameDistributionReferenceTest.java#L46

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java [hunk 1]
```diff
@@ -80,16 +83,30 @@ public ImageName(String fullName, String givenTag) {
 
         // set digest to null as default
         digest = null;
+
+        String algo_reg = "@sha(\\d+):";
```
Comment (rohanKanojia) [inline jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:87]: This would even match invalid algorithms like `sha100`

**Comment by ShantKhatri** [comment]
> @ShantKhatri : Could you please uncomment this line?
> 
> https://github.com/eclipse/jkube/blob/604eb9c8c74a77f963bf1fddf7877bef01f53d82/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameDistributionReferenceTest.java#L46

Okay

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java (hunk 1 above)
Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:87]: okay, I will modify this accordingly.

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java [hunk 2]
```diff
@@ -271,6 +288,7 @@ public static void validate(String image) {
     // Validate parts and throw an IllegalArgumentException if a part is not valid
     private void doValidate() {
         List<String> errors = new ArrayList<>();
+        Pattern digestReg = Pattern.compile("^sha" + hashLen + ":[a-z0-9]{" + hashLen/8 + ",}$");
```
Comment (rohanKanojia) [inline jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:291]: instead of creating a digestReg variable why not modify DIGEST_REGEXP ?

Probably we can create two regexp for this:
- DIGEST_256_REGEXP
- DIGEST_512_REGEXP

then DIGEST_REGEXP can be either of these two algorithms:
private static final String DIGEST_REGEXP = "^(?:" + DIGEST_256_REGEXP + "|" + DIGEST_512_REGEXP + ")";

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java [hunk 3]
```diff
@@ -80,16 +83,30 @@ public ImageName(String fullName, String givenTag) {
...
+        Pattern pattern = Pattern.compile(algo_reg);
+
+        // Create a Matcher object
+        Matcher matcher = pattern.matcher(fullName);
+        // Set Hash length
+        if (matcher.find()) {
+            String numberString = matcher.group(1);
+            hashLen = Integer.parseInt(numberString);
+        }
+        Pattern digestPattern = Pattern.compile("@sha(?:[1-9][0-9]*|0b[01]+|0x[0-9a-fA-F]+)?");
```
Comment (rohanKanojia) [inline jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:98]: Have you tested this regexp? Or could you please point to it's source. This doesn't look right to me. Why are you declaring ranges `[1-9]` and `[0-9]` together? 

Shouldn't `[0-9a-fA-F]` be just `[0-9a-f]`?

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java (hunk 2 above)
Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:291]: I don't know I'm right with approach or not but If we have strictly these two algorithms(As of Image name specifications) then this is the best approach to do like this:
 private static final String DIGEST_REGEXP = "^(?:" + DIGEST_256_REGEXP + "|" + DIGEST_512_REGEXP + ")";
But I was thinking in the way that if in future Image Container specifications will extend with sha then may we have to add one more regex here, yes can update this as  per requirements.
For now I'll modify this according to SHA256 and SHA512 only.

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java (hunk 3 above)
Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:98]: Yes, I have tested it.
For ranging from [1-9] and [0-9]: [1-9] is for first digit which may be from 1-9 and the 2nd one ([0-9]).
I will fix this part.

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java (hunk 2 above)
Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java]: Done !

**Comment by ShantKhatri** [comment]
Hi @rohanKanojia should I uncomment this part too as of these are already fixed:
image

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java [hunk 4]
```diff
@@ -369,5 +369,9 @@ private boolean isRegistryValidPathComponent() {
     // https://github.com/docker/docker/blob/04da4041757370fb6f85510c8977c5a18ddae380/vendor/github.com/docker/distribution/reference/regexp.go#L37
     private static final Pattern TAG_REGEXP = Pattern.compile("^[\\w][\\w.-]{0,127}$");
 
-    private static final Pattern DIGEST_REGEXP = Pattern.compile("^sha256:[a-z0-9]{32,}$");
+    private static final Pattern DIGEST_256_REGEXP = Pattern.compile("[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*:[0-9a-fA-F]{32,}");
+
+    private static final Pattern DIGEST_512_REGEXP = Pattern.compile("[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*:[0-9a-fA-F]{64,}");
```
Comment (rohanKanojia) [inline jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:374]: Could you please check if this works? It's taken from [image-spec for SHA-512](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-512):

> When the algorithm identifier is sha512, the encoded portion MUST match /[a-f0-9]{128}/. Note that [A-F] MUST NOT be used here.

```suggestion
    private static final Pattern DIGEST_512_REGEXP = Pattern.compile("sha512:[0-9a-f]{128}");
```

Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:374]: Sure, yes this one is working fine.

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java [hunk 5]
```diff
@@ -369,5 +369,9 @@ private boolean isRegistryValidPathComponent() {
     // https://github.com/docker/docker/blob/04da4041757370fb6f85510c8977c5a18ddae380/vendor/github.com/docker/distribution/reference/regexp.go#L37
     private static final Pattern TAG_REGEXP = Pattern.compile("^[\\w][\\w.-]{0,127}$");
 
-    private static final Pattern DIGEST_REGEXP = Pattern.compile("^sha256:[a-z0-9]{32,}$");
+    private static final Pattern DIGEST_256_REGEXP = Pattern.compile("[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*:[0-9a-fA-F]{32,}");
```
[the remark this answers is not in the document]
Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:372]: Sure, yes this one is working fine.

File: jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java (hunk 4 above)
Comment (ShantKhatri) [reply jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:374]: Yes, It works.

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
