### PR TITLE
fix (jkube-kit) : Fix `Fabric8HttpUtil.extractAuthenticationChallengeIntoMap` www-authenticate header parsing logic (#2419)

### LINKED ISSUE #2419: Getting `Unauthorized` while pushing helm chart to OCI registry if repository name contains `push`
### Describe the bug

For a valid registry requiring authentication, I kept getting `Unauthorized` error even if I provided the correct credentials. When I debugged the issue, I discovered it had to do with the repository name. My test project name was `jkube-helm-push-oci` which affected this statement:

https://github.com/eclipse/jkube/blob/cc6d239259aab437655a8bfdb76f0328f1170a95/jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptor.java#L98-L99

While requesting token we need to add scope of that token : whether it's for a read (`pull`) or write operation (`push`). By default in first request Www-Authenticate header contains `pull` for read only. We need to manually add `push` to this in order to fetch token for uploading chart. However, this condition turns `false` if the repository name already contains `push` substring.

Rather than comparing scope field in Www-Authenticate header as plain string, we should parse it and then compare only the last segment.

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

Try pushing helm chart to some OCI registry with a chart name containing `push` keyword. Push would always fail

### Expected behavior

Push should be successful when valid credentials are provided regardless of project name

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Linux

### Eclipse JKube Logs

```shell
[ERROR] k8s: Error performing helm push: java.lang.IllegalStateException: Failure in initiating upload request: Unauthorized
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.903 s
[INFO] Finished at: 2023-10-11T12:02:04+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.15-SNAPSHOT:helm-push (default-cli) on project jkube-helm-push-testing: Failure in initiating upload request: Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Sample Reproducer Project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fixes #2419

We try to add push scope to scope field extracted from Www-Authenticate header if it doesn't already exist. This was happening because our `www-authenticate` header parsing logic was flawed and it was omitting `push` scope from `pull,push` scope. We were directly splitting whole string based on commas.

Port OkHttp's [HttpHeaders.parseChallengeHeader](https://github.com/square/okhttp/blob/parent-3.14.9/okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.java#L180) method into our codebase for achieving this. We have runtime dependency on OkHttp, a transitive dependency coming from Fabric8 Kubernetes Client. We needed only `parseChallengeHeader` method for parsing WWW-Authenticate header for fetching authentication challenges. It seemed a better option to port the required method instead of adding okhttp dependency to the project.

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java [hunk 1]
```diff
@@ -71,4 +71,23 @@ public static String toFormData(Map<String, String> formData) throws Unsupported
...
+  public static String appendAdditionalScopeIfNotPresent(String scopeStr, String value) {
+    String[] scopeParts = scopeStr.split(":");
+    if (scopeParts.length > 2) {
+      String pullOrPushScope = scopeParts[2];
+      if (!pullOrPushScope.contains(value)) {
+        scopeParts[2] = scopeParts[2] + "," + value;
+      }
+    }
+    return String.join(":", scopeParts);
+  }
```
Comment (manusa) [inline jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java:92]: This is still not OK.

See the ref for [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)

We first need to identify the appropriate `WWW-Authenticate` header and challenge for the current realm.

Then it might be interesting to parse the challenges as a Map or more specifically as Properties and then retrieve the one that we're interested in (`scope`).

Comment (manusa) [reply jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java:92]: I wouldn't say that that method is parsing the header and reading properties

Comment (manusa) [reply jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java:92]: OK, I think I'm getting confused here.
In any case, that method might benefit from some built-in Java property parsing.
In addition, the signature for the return should probably be changed to something like:
```java
public static List<Properties> extractAuthenticationChallengeIntoMap(HttpResponse<?> response)
```

Comment (manusa) [reply jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java:92]: Please also check the [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) spec documentation.

Probably that's why the parsing is not being done correctly and that might be clearly the source of the problem.

File: jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtilTest.java [hunk 2]
```diff
@@ -49,7 +50,91 @@ void toFormData_whenDataProvidedAsMap_thenCreateFormDataPayload() throws Unsuppo
...
+        .hasSize(2)
+        .containsEntry("Basic realm", "Access to the staging site")
+        .containsEntry("charset", "UTF-8");
+  }
+
+  @Test
+  void extractAuthenticationChallengeIntoMap_whenMultipleChallenges_thenParseDataIntoMap() throws IOException {
+    // Given
+    Map<String, List<String>> responseHeaders = new HashMap<>();
+    responseHeaders.put("WWW-Authenticate", Collections.singletonList("Newauth realm=\"apps\", type=1, title=\"Login to \"apps\"\", Basic realm=\"simple\""));
```
Comment (manusa) [inline jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtilTest.java:83]: This is what I was referring to in the internal call.
I don't think that this is a valid value, it will probably come with escaped quotations marks, as in `title=\"something \\\"escaped\\\"\"`

The idea would be to reuse something that performs the parsing for us. Not sure if Jackson, XML, or something we can leverage

Comment (manusa) [reply jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtilTest.java:83]: So, for example, OkHttp includes the 
HttpHeadrs.parseChallenges method
