### PR TITLE
fixed non final variable code smell

### LINKED ISSUE #1815: [Hacktoberfest] IoUtil fields may be 'final'
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/f7521fe52e886fa3a4abaee28b66809c828dc22d/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java#L135
 
- [x] should be changed to:
```java
    private static final int PROGRESS_LENGTH = 50;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by jhonDoe15**
## Description
Fixes #1815

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes

### CODE REVIEW

**Comment by jhonDoe15** [comment]
Hi @manusa could you pass the PR? the CI is having some glitch

File: jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java [hunk 1]
```diff
@@ -44,8 +47,46 @@ void findOpenPortWhenPortsAreBusy() throws IOException {
...
+
+    @Test
+    void invokeExceptionWhenCouldntFindPort() throws IOException {
+
+        // find open port to occupy
+        int foundPort = IoUtil.getFreeRandomPort(30000, 65000, 1000);
+
+        // use port
+        //noinspection resource
+        ServerSocket ignored = new ServerSocket(foundPort);
```
Comment (manusa) [inline jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java:74]: This statement should be enclosed in a try-with-resources block so that the "ignored" port is closed when the test completes

File: jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java [hunk 2]
```diff
@@ -44,8 +47,46 @@ void findOpenPortWhenPortsAreBusy() throws IOException {
...
+
+        // try to use the used port
+        Exception exception = assertThrows(IllegalStateException.class,
+                () -> IoUtil.getFreeRandomPort(foundPort, foundPort, 3));
+
+
+        String expectedMessage = "Cannot find a free random port in the range [" + foundPort + ", " + foundPort + "] after 3 attempts";
+        String actualMessage = exception.getMessage();
+
+        assertTrue(actualMessage.contains(expectedMessage));
```
Comment (manusa) [inline jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java:84]: This could be converted to a single assertion using AssertJ

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
Thx for going for the extra-mail, really appreciate it. I left a few comments that you can address (if you want) in a subsequent PR.

**Comment by jhonDoe15** [comment]
Hi @manusa! I've fixed the issues and learned along the way (thanks for that 😉) should I create another PR?
