### PR TITLE
fix (jkube-kit/enricher) : Add trailing newline for multiline strings in labels/annotations (#1829)

### LINKED ISSUE #1829: YAML Multiline block indicator issue
### Describe the bug

When adding ISTIO configuration, via the annotations config, it is setting a [Block Chomping Indicator](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator) to clip the new line, where it needs to retain the new line.
[Yaml Multiline](https://yaml-multiline.info/)
[ISTIO Config](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/)

POM Plugin config 
```
<resources>
	<annotations>
		<all>
			<property>
				<name>proxy.istio.io/config</name>
				<value>proxyMetadata:
    ISTIO_META_DNS_CAPTURE: "false"
holdApplicationUntilProxyStarts: true</value>
			</property>
		</all>
	</annotations>
</resources>
```

Deployment.yml Output 
```  
metadata:
    annotations:
      proxy.istio.io/config: |-
        proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "false"
        holdApplicationUntilProxyStarts: true
```

As you can see above the deployment yaml has "|-" which causes the annotation to not work with ISTIO 

### Eclipse JKube version

1.9.1

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.3

### Gradle version

_No response_

### Steps to reproduce

1. Configure the maven plugin - annotation - with multiline text. 
2. Build it using mvn k8s:resource 
3. Check target output

### Expected behavior

Expected output 
```
metadata:
    annotations:
      proxy.istio.io/config:  |
        proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "false"
        holdApplicationUntilProxyStarts: true
```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows, Linux

### Eclipse JKube Logs

_No response_

### Sample Reproducer Project

Sits on commercial infra 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fixes #1829

Add a trailing newline in case of multiline values in labels and annotations in MetadataVisitor

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by sunix — APPROVED** [review]

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java [hunk 1]
```diff
@@ -126,6 +126,13 @@ private static MetaDataConfig getLabels(ResourceConfig resourceConfig) {
     return Optional.ofNullable(resourceConfig).map(ResourceConfig::getLabels).orElse(new MetaDataConfig());
   }
 
+  private String appendTrailingNewLineIfMultiline(String value) {
+    if (value.contains(System.lineSeparator()) && !value.endsWith(System.lineSeparator())) {
```
Comment (sunix) [inline jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java:130]: just wondering, what if it ends with `\n `

Comment (rohanKanojia) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java:130]: I checked this scenario and found this:

When I provide such configuration in XML configuration, result is unaffected because XML configuration seems to swallow trailing newline https://github.com/eclipse/jkube/issues/1829#issuecomment-1314221042

In the case of Groovy DSL configuration, It seems to generate wrong output like this:
```yaml
  metadata:
    annotations:
      multiline/config: "proxyMetadata:\n ISTIO_META_DNS_CAPTURE: \"false\"\nholdUntilProxyStarts:\
        \ true\n    \n"
```

Not sure if calling `value.trim()` would help since it removes trailing newline as wel.

**Review by manusa — APPROVED** [review]

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java (hunk 1 above)
Comment (manusa) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java:130]: Is there going to be any follow up on this?
