### PR TITLE
Fix #246: Dockerfile custom interpolation is broken

### LINKED ISSUE #246: Dockerfile custom interpolation is broken
## Description
After #80, Dockerfile interpolation configured by [BuildConfiguration#filter](https://github.com/eclipse/jkube/blob/107d3bfcd4ac7bb7cc47363865377f2de3fa3200/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java#L72) is now broken. Custom separators (or disabling) is no longer working since the new [JKubeDockerfileInterpolator](https://github.com/eclipse/jkube/blob/107d3bfcd4ac7bb7cc47363865377f2de3fa3200/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolator.java#L20) is not configurable.

Tests should be ported from [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin/blob/e683ca7a6063d60854868ce4a7716829621e65b2/src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java#L93) so that behavior is exactly the same as [FixedStringSearchInterpolator](https://github.com/fabric8io/docker-maven-plugin/blob/e683ca7a6063d60854868ce4a7716829621e65b2/src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java#L124) with [tests](https://github.com/sonatype/plexus-interpolation/blob/16f8c521c60021fbac3295f0ed10ba5bc6cfdc9a/src/test/java/org/codehaus/plexus/interpolation/fixed/FixedStringSearchInterpolatorTest.java#L32).

According to documentation, interpolator configuration can be any of:
- No configuration `StringUtils.isBlank(BuildConfiguration#filter)`
- Disabled (`<filter>false</filter>`)  `BuildConfiguration#filter equalsIgnoreCase("false")`
- Custom interpolator (single character or prefix`*`suffix):  `<filter>@</filter>`,  `<filter>${*}</filter>`

See [DMP logic](https://github.com/fabric8io/docker-maven-plugin/blob/e683ca7a6063d60854868ce4a7716829621e65b2/src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java#L163).

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #246 

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerFileUtil.java [hunk 1]
```diff
@@ -103,15 +102,36 @@ private DockerFileUtil() {}
...
      * @throws IOException if there's a problem while performin IO operations.
      */
-    public static String interpolate(File dockerFile, Properties properties) throws IOException {
+    public static String interpolate(File dockerFile, Properties properties, Map<String, String> customInterpolationParams) throws IOException {
         StringBuilder ret = new StringBuilder();
         try (BufferedReader reader = new BufferedReader(new FileReader(dockerFile))) {
             String line;
             while ((line = reader.readLine()) != null) {
-                ret.append(JKubeDockerfileInterpolator.interpolate(line, properties)).append(System.lineSeparator());
+                ret.append(JKubeDockerfileInterpolator.interpolate(line, properties, customInterpolationParams)).append(System.lineSeparator());
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerFileUtil.java:134]: No longer used, since we have `public static String interpolate(File dockerFile, Properties properties, String filter) throws IOException {, please remove (test too)

File: jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolator.java [hunk 2]
```diff
@@ -13,37 +13,197 @@
...
-        delimiters.put("@", "@");
-        delimiters.put("${", "}");
-    }
 
     private JKubeDockerfileInterpolator() { }
 
-    public static String interpolate(String line, Properties properties) {
+    public static String interpolate(String line, Map<String, String> context, String filter) {
+        return interpolate(line, context, getExpressionMarkersFromFilter(filter));
+    }
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolator.java:28]: Unused code, please remove

File: jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolator.java [hunk 3]
```diff
@@ -13,37 +13,197 @@
...
+     * @param line              string provided with parameters
+     * @param context           properties provided as hashmap
+     * @param expressionMarkers additional markers to use for parameterized expressions
+     * @return string with properties parameters replaced
+     */
+    public static String interpolate(String line, Map<String, String> context, Map<String, String> expressionMarkers) {
+        Properties p = new Properties();
+        context.forEach(p::put);
+        return checkForPropertiesInLine(line, p, expressionMarkers, null);
+    }
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolator.java:46]: Unused code, please remove.
If you created either of these unused methods to comply with tests, just update the tests to provide the necessary input parameters for the functions.
