### PR TITLE
fix (jkube-kit) : Generate yaml files for different environments (#1218)

### LINKED ISSUE #1218: Generate yaml files for different environments
### Description

I need to generate different yaml files for different environments, not only for the same environment but also different configurations for the same environment. It would be useful to have a basic templating system to be used for the different targets and specific modifications for the different combinations, it could use a system based on directories, one `commons` and one for each target (environment or deployment) for example.

### Related to

- https://gitter.im/eclipse/jkube?at=618245467db1e3753e7ba861

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1218 

Modify ResourceServiceConfig to recieve a list of files as resourceDirs
instead of receiving a single resourceDir. Resource fragments in these
files can be combined while generating resources.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/MultiEnvironmentsIT.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+  @Test
+  public void k8sResource_whenRun_generatesK8sManifestsContainingConfigMap() throws IOException, ParseException {
+    // When
+    final BuildResult result = gradleRunner.withITProject("multi-environments")
+        .withArguments("build", "-Pjkube.environment=" + environment, "k8sResource", "--stacktrace")
+        .build();
+    // Then
+    ResourceVerify.verifyResourceDescriptors(gradleRunner.resolveDefaultKubernetesResourceFile(),
+        gradleRunner.resolveFile("expected", environment.replace(",", "and"), "kubernetes.yml"));
```
Comment (manusa) [inline gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/MultiEnvironmentsIT.java:57]: This makes it hard to read. It's better if you define another parameter for the expected directory (just like we did for other tests `expectedDirectory`).

nit: Also, if you add the new parameter, it would be nice if the expected directories were renamed from `commonanddev` and `commonandprod` to `common-and-dev` and `common-and-prod` so they are more readable.

File: jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ResourceUtil.java [hunk 2]
```diff
@@ -134,11 +134,18 @@ private static ObjectMapper getObjectMapper(ResourceFileType resourceFileType) {
...
-            return new File(resourceDir, environment);
+    public static List<File> getFinalResourceDirs(File resourceDir, String environmentAsCommaSeparateStr) {
+        List<File> resourceDirs = new ArrayList<>();
+
+        if (resourceDir != null && StringUtils.isNotEmpty(environmentAsCommaSeparateStr)) {
+            String[] environments = environmentAsCommaSeparateStr.split(",");
+            for (String environment : environments) {
+                resourceDirs.add(new File(resourceDir, environment.trim()));
+            }
+        } else if (StringUtils.isEmpty(environmentAsCommaSeparateStr)) {
```
Comment (manusa) [inline jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ResourceUtil.java:145]: I know we were using `isNotEmpty` before, but maybe it's a better idea to change this to `isBlank` instead of `isEmpty`. This would prevent failures in case the environment is set to a blank string.

File: jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceServiceConfig.java [hunk 3]
```diff
@@ -35,7 +36,7 @@
 public class ResourceServiceConfig {
 
   private JavaProject project;
-  private File resourceDir;
+  private List<File> resourceDirs;
```
Comment (manusa) [inline jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceServiceConfig.java:39]: You could annotate this field with the `@Singular` annotation to make the builder more user-friendly.

**Comment by manusa** [comment]
UndeployMojo and service have a different resource configuration logic. We need to unify this so that resources are configured uniformly for all Tasks and Mojos (Resource, Apply, Watch, Undeploy) ----> Discuss & Create new issue

**Review by manusa — APPROVED** [review]
