### PR TITLE
 ISSUE#891 busybox image name is hardcoded in VolumePermissionEnrich…

### LINKED ISSUE #891: busybox image name is hardcoded in VolumePermissionEnricher class, need to make it as config
### Description

**busybox** image name is hardcoded in [VolumePermissionEnricher.java Line 115](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L115).
Now a days every one have their own ECR registries maintained.Few people are using Dockerhub pro version to pull images.
Due to this , we are getting rate limiting issue from Dockerhub. So Please make this image name as config for enricher.

Where is this code :
```
return new ContainerBuilder()
                        .withName(ENRICHER_NAME)
                        .withImage("busybox")
                        .withImagePullPolicy("IfNotPresent")
                        .withCommand(createChmodCommandArray(mountPoints))
                        .withVolumeMounts(createMounts(mountPoints))
                        .build();
```

Thanks to @rohanKanojia for providing  hint on fix.
How to fix:
Maybe we can add another field in enricher configuration to override image name: https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L57

### Info

* Eclipse JKube version : master
* Maven version (`mvn -v`) : Apache Maven 3.6.3
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :
* Use Dockerhub as registry without credentials. recently Dockerhub has introduced RateLimiting for Pulling images.

### PR DESCRIPTION
**Pull request by kumar-cloud**
## Description

Add Init Conatiner Image Name as configurable
 1. Added new ENUM for ImageName
 2. Used default value as busybox

It helps in avoiding ratelimiting from some  Image regsiteries and provide user custom images. 

Fix #891

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Could you please add some test to validate whether the fix actually works?

**Comment by rohanKanojia** [comment]
Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by kumar-cloud** [comment]
> Welcome, Thanks a lot for contributing to Eclipse JKube 👍,
> 
> In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
> 
> ```
> # (Optional): Configure Git User and Email
> git config user.name "Your Name"
> git config user.email "your_email@example.com"
> 
> # Amend your previous commit with signed off footer
> git commit --amend --signoff
> ```

I have created... may be using wrong user

**Comment by kumar-cloud** [comment]
I have added testcases for the same

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java [hunk 1]
```diff
@@ -112,7 +113,7 @@ private Container createPvInitContainer(PodSpec podSpec) {
                 Map<String, String> mountPoints = extractMountPoints(podSpec);
                 return new ContainerBuilder()
                         .withName(ENRICHER_NAME)
-                        .withImage("busybox")
+                        .withImage(getConfig(Config.IMAGE_NAME,Config.IMAGE_NAME.getDefaultValue()))
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java:116]: This is not necessary, the default value is retrieved from the config key automatically:
```suggestion
                        .withImage(getConfig(Config.IMAGE_NAME))
```

Comment (kumar-cloud) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java:116]: ok noted

Comment (rohanKanojia) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java:116]: > When this will be merged into master?



I understand it's your first time working with some open source project but please have some patience. We are going to merge it as soon as it's ready to merge. Right now you need to update this patch as per the changes requested by Marc.

**Comment by Amr116** [comment]
Thank you guys for your work on solving this issue.
It has been blocking us, and we looking forward to the new release that contains the fix.

@kumar-cloud  Could you please expose an xml example about how to define the init container image  based on your fix.
Thank you.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
> Thank you guys for your work on solving this issue.
> It has been blocking us, and we looking forward to the new release that contains the fix.
> 
> @kumar-cloud Could you please expose an xml example about how to define the init container image based on your fix.
> Thank you.

Once this PR is merged you can use the new option either by setting the property: `jkube.enricher.jkube-volume-permission.imageName` or via XML:
```xml
<enricher>
    <config>
        <jkube-volume-permission>
            <imageName>your-image</imageName>
        </jkube-volume-permission>
    </config>
</enricher>
```

**Comment by Amr116** [comment]
> > Thank you guys for your work on solving this issue.
> > It has been blocking us, and we looking forward to the new release that contains the fix.
> > @kumar-cloud Could you please expose an xml example about how to define the init container image based on your fix.
> > Thank you.
> 
> Once this PR is merged you can use the new option either by setting the property: `jkube.enricher.jkube-volume-permission.imageName` or via XML:
> 
> ```
> <enricher>
>     <config>
>         <jkube-volume-permission>
>             <imageName>your-image</imageName>
>         </jkube-volume-permission>
>     </config>
> </enricher>
> ```

Thank you @kumar-cloud 
we are waiting eagerly for this fix to be merged ;)

**Comment by Amr116** [comment]
Hi @kumar-cloud 
Please create account for you at https://accounts.eclipse.org/user/register?destination=legal/eca to pass the account policy validation
Screenshot 2021-09-17 at 13 26 53

**Review by manusa — APPROVED** [review]
LGTM, thx!
