### PR TITLE
fix: removes potential command-line injection from secret in SpringBootWatcher

### LINKED ISSUE #2166: Potential command line injection from secret
### Description

Mirror of `TOB-JKUBE-2`.

As part of the Spring Boot watcher functionality, JKube executes a second Java process. The
command line for this process is crafted in an unsafe way, by interpolating an arbitrary
secret in the command line. This command line is then tokenized by separating on spaces.
If the secret contains spaces, this can allow an attacker to add arbitrary arguments and
command line flags and modify the behavior of this command execution.

https://github.com/eclipse/jkube/blob/12edf4a2f947ad1e0b2b44d8317a6052097f93af/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java#L163-L166

### PR DESCRIPTION
**Pull request by manusa**
## Description

Fix #2166 

Adds integration test for SpringBootWatcher.
Removes potential command-line injection from secret in SpringBootWatcher

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+      && command[1].equals("-cp")
+      && command[2].contains(
+      absolutePath("spring-boot-lib.jar") + File.pathSeparator + absolutePath("spring-boot-devtools.jar"))
+      && command[3].equals("-Dspring.devtools.remote.secret=this-is-a-test")
+      && command[4].equals("org.springframework.boot.devtools.RemoteSpringApplication")
+      && command[5].matches("^http://localhost:\\d+$")
+    ));
+  }
+
+  String absolutePath(String jar) {
```
Comment (rohanKanojia) [inline jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java:126]: Why not private?

File: jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
+package org.eclipse.jkube.springboot.watcher;
```
Comment (rohanKanojia) [inline jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java:1]: license header missing

**Review by rohanKanojia — APPROVED** [review]
