### PR TITLE
Fix #548: Define property for skipping cluster autodetect/offline mode

### LINKED ISSUE #548: Define property for skipping cluster autodetect mode and go straight to the Kubernetes offline mode
It would be nice if we could tell JKube to work offline on resources and push goals at least, 
so it skips the cluster autodetect mode, which can fail with ugly stacktraces if the  environment has a cluster but semiconfigured (for instant the aws credentials), and go straight to Kubernetes mode like the regular fallback does.
This prevents any unwanted interaction with the local cluster
  

Thanks mates!

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
    
+ Add a property `jkube.offline` which which jkube would skip
   cluster auto detection and go straight to offline mode.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [X] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java [hunk 1]
```diff
@@ -68,62 +68,33 @@
     private LazyBuilder<UndeployService> undeployService;
     private LazyBuilder<MigrateService> migrateService;
     private LazyBuilder<DebugService> debugService;
+    private final boolean connectToCluster;
```
Comment (manusa) [inline jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java:71]: Is there any specific reason to call the configuration offline and then the Service Hub variable `connectToCluster`?

If the offline configuration is only used for this purpose and the `connectToCluster` variable is only set by the offline configuration, it would make much more sense to name them the same. It would also help in the future when searching for configurations and debugging.

File: jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java [hunk 2]
```diff
@@ -168,4 +139,57 @@ public DebugService getDebugService() {
         return debugService.get();
     }
 
+    private void initClusterDependentServiceLazyBuilders() {
```
Comment (manusa) [inline jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java:142]: Not all of these services seem to be dependent on cluster.
```suggestion
    private void initClusterAccessAndLazyBuilders() {
```

File: jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java [hunk 3]
```diff
@@ -59,10 +61,15 @@
   private BuildServiceConfig buildServiceConfig;
 
   private JKubeServiceHub.JKubeServiceHubBuilder commonInit() {
+    return commonInit(true);
+  }
+
+  private JKubeServiceHub.JKubeServiceHubBuilder commonInit(boolean connectToCluster) {
```
Comment (manusa) [inline jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java:67]: Follow the existing approach and take advantage of the builder.

If you were to add parameters for every override, then tests would be less declarative, fluent, and readable.

e.g. 
In line 118 you are overrding the cluster access **and** the platform mode.
---> `commonInit().platformMode(RuntimeMode.KUBERNETES).offline(true)`

**Review by manusa — APPROVED** [review]
LGTM, thx!
