### PR TITLE
Fix #1180: SpringBootWatcher uses default namespace even if other namespace is configured

### LINKED ISSUE #1180: k8s:watch uses default namespace even if other namespace is configured
### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: REDACTED
Java version: 17, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-162-generic", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version :
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Issue

I am working on a Rancher cluster

Since it involves a Rancher cluster, I can't give a good guide on how to reproduce, but the issue is pretty straight forward. When I am trying to run `mvn k8s:resource k8s:build k8s:push k8s:watch`, my docker image is built, pushed and deployed correctly (I can find the deployment in the cluster) but I get the following error:
```
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.5.1:watch (default-cli) on project spring-kube-demo: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.5.1:watch failed: Failure executing: GET at: https://rancher-cluster.my-company.com/k8s/clusters/local/api/v1/namespaces/default/pods?labelSelector=app%3Dspring-kube-demo%2Cprovider%3Djkube%2Cgroup%3Dcom.mycompany.mydepartment. Message: Forbidden! User myuser doesn't have permission. pods is forbidden: User "myuser" cannot list resource "pods" in API group "" in the namespace "default". -> [Help 1]
```

Not providing access to the default namespace is by design in Rancher clusters. I do have the namespace configured in my `pom.xml`:
```
<plugin>
  <groupId>org.eclipse.jkube</groupId>
    <artifactId>kubernetes-maven-plugin</artifactId>
    <version>1.5.1</version>
    <configuration>
      <namespace>development</namespace>
         <images>
          ...
        </images>
    </configuration>
</plugin>    
```

I would expect `k8s:watch` to use the configured namespace.

[Full stack trace](https://gist.github.com/petergarnaes/554c3c25f1bb256b331a5a55c94aa505)

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1180

No namespace is specified to Watcher while delegating watch task from
Mojos/Tasks to JKube Kit. Right now Watcher was just picking namespace
from `clusterAccess.getNamespace()` (namespace provided in current
context in `.kube/config`).

Add an additional namespace parameter in Watcher.watch(...) method for
providing configured namespace.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/Watcher.java [hunk 1]
```diff
@@ -38,7 +38,11 @@
      * Watch the resources and kick a rebuild when they change.
      *
      * @param configs all image configurations
+     * @param namespace namespace in which resources are deployed
+     * @param resources list of resources applied
+     * @param mode {@link PlatformMode}
+     * @throws Exception in case of any failure
      */
-    void watch(List<ImageConfiguration> configs, Collection<HasMetadata> resources, PlatformMode mode) throws Exception;
+    void watch(List<ImageConfiguration> configs, String namespace, Collection<HasMetadata> resources, PlatformMode mode) throws Exception;
```
Comment (sunix) [inline jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/Watcher.java:46]: I am wondering if we can provide a method with the namespace and another one without.
Passing `null` sounds not ideal to me.

**Review by sunix — APPROVED** [review]

**Review by manusa — APPROVED** [review]
