### PR TITLE
Fix #939: Move KubernetesBuildTask's common initialization logic to a helper class

### LINKED ISSUE #939: Move KubernetesBuildTask's initialization logic to a helper class
### Description

While adding KubernetesPushTask, I noticed it's implementation for `initJKubeServiceHubBuilder()` and `buildServiceConfigBuilder()` are same as  KubernetesBuildTask's `initJKubeServiceHubBuilder()` and `buildServiceConfigBuilder()`. We should move this to a helper class in order to avoid duplication.

If I try making KubernetesPushTask extend KubernetesBuildTask, I get a circular dependency related error while invoking KubernetesPushTask(since I've defined KubernetesBuildTask precedence over KubernetesPushTask):
```
spring-boot-camel-complete : $ gradle k8sPush
Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:k8sPush
\--- :k8sPush (*)

(*) - details omitted (listed previously)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

```

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #939
KubernetesBuildTask's initJKubeServiceHubBuilder() and
buildServiceConfigBuilder() are same as implementation for
KubernetesPushTask.

Moving them to a helper class BuildTaskHelper in order to reuse them.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/BuildTaskHelper.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    ImagePullManager imagePullManager = createImagePullManager(
+      kubernetesExtension.getImagePullPolicy().getOrElse("Always"),
+      kubernetesExtension.getAutoPull().getOrElse("true"),
+      javaProject.getProperties());
+    builder.buildServiceConfig(buildServiceConfigBuilder
+      .imagePullManager(imagePullManager)
+      .enricherTask(e -> {
+        enricherManager.enrich(PlatformMode.kubernetes, e);
+        enricherManager.enrich(PlatformMode.openshift, e);
+      })
```
Comment (manusa) [inline gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/BuildTaskHelper.java:71]: Let's take a look at this together, but since this builder is generated downstream it might make more sense to configure it there.

File: gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/BuildTaskHelper.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+import org.eclipse.jkube.kit.config.resource.BuildRecreateMode;
+import org.eclipse.jkube.kit.config.resource.PlatformMode;
+import org.eclipse.jkube.kit.config.service.BuildServiceConfig;
+import org.eclipse.jkube.kit.config.service.EnricherManager;
+import org.eclipse.jkube.kit.config.service.JKubeServiceHub;
+
+import static org.eclipse.jkube.kit.build.service.docker.DockerAccessFactory.DockerAccessContext.DEFAULT_MAX_CONNECTIONS;
+import static org.eclipse.jkube.kit.build.service.docker.ImagePullManager.createImagePullManager;
+
+public class BuildTaskHelper {
```
Comment (manusa) [inline gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/BuildTaskHelper.java:32]: If this is going to be reused by Push tasks (or others), why are you calling it BuildTaskHelper.

Maybe something like `TaskUtil` in the `org.eclipse.jkube.gradle.plugin.task` package can be reused for other composite methods applicable to the rest of the tasks.

**Review by manusa — APPROVED** [review]
