### PR TITLE
fix (jkube-kit/resource/helm) : Helm `values.yaml` sorted alphabetically

### LINKED ISSUE #2389: Helm: values.yaml sorted alphabetically
## Description

To allow reproducible builds and prevent diffs when committing the generated `values.yaml` file, the values should be sorted in a predictable and reproducible way (alphabetically should work).

Adding a final sort step to [`createValuesYaml`](https://github.com/eclipse/jkube/blob/331cb3c1476a97df1f0d2b4354aebefef2012e4c/jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L351) or
[`collectParameters`](https://github.com/eclipse/jkube/blob/331cb3c1476a97df1f0d2b4354aebefef2012e4c/jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java#L362C49-L362C49) should suffice.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fixes #2389

Add additional Jackson configuration `SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS` to sort keys alphabetically. 

This would change the ordering of YAML content that is written by JKube. Not sure whether users might be relying on ordering. If yes, it can be considered a breaking change.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2509 (_2023-12-29T05:07:11Z_)

:gear: [JKube E2E Tests (7353930736)](https://github.com/jkubeio/ci/actions/runs/7353930736) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2509)](https://github.com/jkubeio/ci/actions/runs/7353930736/job/20020530799)

**Review by manusa — CHANGES_REQUESTED** [review]
If I'm not mistaken, this wont sort nested values such as:
```yaml
first:
  second:
    third: 1
    fourth: two
```

File: jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java [hunk 1]
```diff
@@ -213,6 +213,33 @@ void generateHelmCharts_withValidValuesYamlFragment_usesMergedValues() throws Ex
...
+    assertThat(savedValues.keySet())
+        .containsExactly("image", "ingress", "replaceableProperty", "replicaCount", "service", "serviceAccount");
+    assertThat(((Map<String, ?>) savedValues.get("ingress")).keySet())
+        .containsExactly("annotations", "className", "enabled", "hosts", "tls");
+    assertThat(((Map<String, ?>) savedValues.get("image")).keySet())
+        .containsExactly("pullPolicy", "repository", "tag");
+    assertThat(((Map<String, ?>) savedValues.get("serviceAccount")).keySet())
+        .containsExactly("annotations", "create", "name");
+    assertThat(((Map<String, ?>) savedValues.get("service")).keySet())
+        .containsExactly("port", "type");
```
Comment (manusa) [inline jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java:240]: I like the new solution, efficient and simple.

However, the test doesn't completely prove it works.

It might be better to feed a specifically crafted `values.yaml` file in the `Given` section with unsorted, nested values.

And then verify the generated `values.yaml` file text contents (not deserializing it) in the `Then` section.

**Review by manusa — CHANGES_REQUESTED** [review]

**Review by manusa — APPROVED** [review]
