### PR TITLE
Fix #184: IngressEnricher seems to be broken

### LINKED ISSUE #184: IngressEnricher seems to be broken
## Description

The following code seems to be ignoring the `ingressBuilder`
 ([see FMP version](https://github.com/fabric8io/fabric8-maven-plugin/blob/bb70ea8e9522124a047730107a2df4460f356d9c/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/IngressEnricher.java#L112)).

https://github.com/eclipse/jkube/blob/9e3d67371e8c12bc8aa6288acacc83d1f796ea96/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java#L62-L80

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #184 

Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1730

### CODE REVIEW

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java [hunk 1]
```diff
@@ -98,7 +125,7 @@ private Integer getServicePort(ServiceBuilder serviceBuilder) {
                 }
             }
         }
-        return null;
+        return Integer.parseInt("0");
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java:128]: ?
```suggestion
        return 0;
```

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java [hunk 2]
```diff
@@ -119,23 +146,33 @@ public void visit(IngressBuilder builder) {
...
-    private boolean isExposedService(Service service) {
-        ObjectMeta metadata = service.getMetadata();
-        if (metadata != null) {
-            Map<String, String> labels = metadata.getLabels();
-            if (labels != null) {
-                if ("true".equals(labels.get("expose")) || "true".equals(labels.get(JKubeAnnotations.SERVICE_EXPOSE_URL.value()))) {
+    /**
+     * Should we try to create an external URL for the given service?
+     * <p/>
+     * By default lets ignore the kubernetes services and any service which does not expose ports 80 and 443
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java:152]:
```suggestion
     * 
     * <p> By default lets ignore the kubernetes services and any service which does not expose ports 80 and 443
```

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java [hunk 3]
```diff
@@ -104,6 +97,77 @@ private RoutePort createRoutePort(ServiceBuilder serviceBuilder) {
...
+            if (!hasRoute(listBuilder, name)) {
+                if (StringUtils.isNotBlank(routeDomainPostfix)) {
+                    routeDomainPostfix = prepareHostForRoute(routeDomainPostfix, name);
+                } else {
+                    routeDomainPostfix = "";
+                }
+
+                RoutePort routePort = createRoutePort(serviceBuilder);
+                if (routePort != null) {
+                    // TODO one day lets support multiple ports on a Route when the model supports it
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:154]: Remove this comment and create an issue instead

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java [hunk 4]
```diff
@@ -104,6 +97,77 @@ private RoutePort createRoutePort(ServiceBuilder serviceBuilder) {
...
+                    RouteBuilder routeBuilder = new RouteBuilder().
+                            withMetadata(serviceMetadata).
+                            withNewSpec().
+                            withPort(routePort).
+                            withNewTo().withKind("Service").withName(name).endTo().
+                            withHost(routeDomainPostfix.isEmpty() ? null : routeDomainPostfix).
+                            endSpec();
+
+                    // removing `expose : true` label from metadata.
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:163]: What does this imply?

File: kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java [hunk 5]
```diff
@@ -86,12 +60,6 @@
     public static final String DEFAULT_KUBERNETES_MANIFEST = "${basedir}/target/classes/META-INF/jkube/kubernetes.yml";
     public static final String DEFAULT_OPENSHIFT_MANIFEST = "${basedir}/target/classes/META-INF/jkube/openshift.yml";
 
-    /**
-     * The domain added to the service ID when creating OpenShift routes
-     */
-    @Parameter(property = "jkube.domain")
-    protected String routeDomain;
```
Comment (manusa) [inline kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java:93]: Is this parameter still supported via properties?

File: kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java [hunk 6]
```diff
@@ -163,16 +131,6 @@
...
 
-    /**
-     * Should we create external Ingress/Routes for any LoadBalancer Services which don't already have them.
-     * <p>
-     * We now do not do this by default and defer this to the
-     * <a href="https://github.com/jkubeio/exposecontroller/">exposecontroller</a> to decide
-     * if Ingress or Router is being used or whether we should use LoadBalancer or NodePorts for single node clusters
-     */
-    @Parameter(property = "jkube.deploy.createExternalUrls", defaultValue = "false")
-    private boolean createExternalUrls;
```
Comment (manusa) [inline kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java:174]: Is this parameter still supported via properties?

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java (hunk 4 above)
Comment (rohanKanojia) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:162]: I think it's about removing `expose=true` labels added by [ExposeEnricher](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ExposeEnricher.java)

File: kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java (hunk 5 above)
Comment (rohanKanojia) [reply kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java:93]: I have moved this to ResourceMojo since route/ingress generation is no longer part of apply goal

File: kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java (hunk 6 above)
Comment (rohanKanojia) [reply kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java:174]: I have moved this to resource mojo. This flag enables `Ingress` generation

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_faq.adoc [hunk 7]
```diff
@@ -121,3 +121,27 @@ spec:
 
 Where the above defines the `PersistentVolumeClaim` called `foo` which is then mounted into the container at `/whatnot`
 
+=== How do I generate Ingress for my generated Service?
+`Ingress` generation is supported by Eclipse JKube for `Service` objects of type `LoadBalancer`. In order to generate `Ingress` you need to enable `jkube.createExternalUrls` property to `true` and `jkube.domain` property to desired host suffix, it would be appended to your service name for host value. You can also also provide a host for it in XML config like this:
+```
+  <plugin>
+    <groupId>org.eclipse.jkube</groupId>
+    <artifactId>kubernetes-maven-plugin</artifactId>
+    <version>${project.version}</version>
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_faq.adoc:130]: Please use Asciidoc variables that will be replaced upon documentation generation
```suggestion
    <artifactId>{plugin}</artifactId>
    <version>{version}</version>
```

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java (hunk 4 above)
Comment (manusa) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:162]: Yes, I see that. But what does that expose=true label > ExposeEnricher do?

I think it something fabric8 only related (hence deprecated) but I may be wrong

https://blog.fabric8.io/additional-kubernetes-controllers-from-fabric8-you-can-use-with-your-microservice-3126a2c4c132
https://github.com/jenkins-x/exposecontroller

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/Constants.java [hunk 8]
```diff
@@ -20,5 +20,6 @@
 public class Constants {
     public static final String RESOURCE_SOURCE_URL_ANNOTATION = "maven.jkube.io/source-url";
     public static final String RESOURCE_APP_CATALOG_ANNOTATION = "maven.jkube.io/app-catalog";
+    public static final String EXPOSE_LABEL = "expose";
```
Comment (manusa) [inline jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/Constants.java:23]: In general this is considered a bad idea and an anti-pattern (https://en.wikipedia.org/wiki/Constant_interface#:~:text=In%20general%2C%20collecting%20system%20constants,be%20considered%20an%20anti%2Dpattern.)

It's better to keep constants near their usage so that context doesn't get lost. Having an `EXPOSE_LABEL` constant with no other context makes it very hard to understand what its purpose is.
