### PR TITLE
fix (jkube-kit) : Remove ExposeEnricher (#1309)

### LINKED ISSUE #1309: ExposeEnricher removal/update
### Description
The [ExposeEnricher](https://github.com/eclipse/jkube/blob/bc2a7c809087451bb49b1a62299c0bdedacbea8b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ExposeEnricher.java) seems to be completely outdated.

The purpose of this Enricher seems to be just to add an `expose` label to the generated service. This label was probably consumed by one of the Fabric8 microservices. Or maybe there's an internal OpenShift feature that relies on this?

### AC
- [x] [Analyze purpose](https://github.com/eclipse/jkube/issues/1309#issuecomment-1092895078)
- [x] Remove class
- [x] Remove from `enricher-default` service definitions
- [x] Remove from profiles
- [x] Remove from docs

### Service Exposure behavior

The behavior for the exposure of Services must be preserved regardless of the removal of the enricher.

- Services with the following conditions are exposed:
  - Single port.
  - Not named `kubernetes` or `kubernetes-ro`.
  - Don't have an `expose: false` label.
- Routes:
  - Active by default. Can be deactivated **globally** by using the `jkube.openshift.generateRoute` or `jkube.enricher.jkube-openshift-route.generateRoute` properties.
  - Services with web ports (80, 443, 8080, 9080, 9090, 9443) will be automatically exposed.
  - Non web ports can be exposed by:
    - Labeling the service with `expose: true`.
    - Using the `jkube.createExternalUrls` property.
  - Can be disabled for a specific Service (**individually**) by labeling it with `expose: false`.
- Ingresses:
  - Disabled by default. Can be activated by using the `jkube.createExternalUrls` property.
  - All Services (matching the exposure conditions will be exposed)
  - Can be disabled for a specific Service (**individually**) by:
    - Labeling it with `expose: false`.
    - Providing an Ingress fragment for that Service (Ingress has the same name).

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1309

- Remove all occurrences of `ExposeEnricher` from project.
- Service exposure behavior:
  - Services with the following conditions are exposed:
    - Single port.
    - Not named `kubernetes` or `kubernetes-ro`.
    - Don't have an `expose: false` label.
  - Routes:
    - Active by default. Can be deactivated **globally** by using the `jkube.openshift.generateRoute` or `jkube.enricher.jkube-openshift-route.generateRoute` properties.
    - Services with web ports (80, 443, 8080, 9080, 9090, 9443) will be automatically exposed.
    - Non web ports can be exposed by:
      - Labeling the service with `expose: true`.
      - Using the `jkube.createExternalUrls` property.
    - Can be disabled for a specific Service (**individually**) by labeling it with `expose: false`.
  - Ingresses:
    - Disabled by default. Can be activated by using the `jkube.createExternalUrls` property.
    - All Services (matching the exposure conditions will be exposed)
    - Can be disabled for a specific Service (**individually**) by:
      - Labeling it with `expose: false`.
      - Providing an Ingress fragment for that Service (Ingress has the same name).

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [X] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
I think E2E tests should pass once https://github.com/jkubeio/jkube-integration-tests/pull/139 gets merged

**Comment by manusa** [comment]
We've removed a lot of functionality in this PR, we should discuss and re-evaluate alternatives.

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NetworkingV1IngressGenerator.java [hunk 1]
```diff
@@ -57,7 +56,7 @@ protected static Ingress generate(KubernetesListBuilder listBuilder, ServiceBuil
         if (serviceMetadata == null) {
             log.info("No Metadata for service! ");
         }
-        if (isExposedService(serviceMetadata) && shouldCreateExternalURLForService(serviceBuilder, log)) {
+        if (shouldCreateExternalURLForService(serviceBuilder, log)) {
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NetworkingV1IngressGenerator.java:59]: The behavior of this might now be different, since before we were checking for Web Ports (See `ExposeEnricher.WEB_PORTS`)
Is this addressed elsewhere?

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java [hunk 2]
```diff
@@ -104,7 +103,7 @@ private void addRoute(KubernetesListBuilder listBuilder, ServiceBuilder serviceB
         ObjectMeta serviceMetadata = serviceBuilder.buildMetadata();
 
         if (serviceMetadata != null && StringUtils.isNotBlank(serviceMetadata.getName())
-                && hasExactlyOneServicePort(serviceBuilder, serviceMetadata.getName()) && isExposedService(serviceMetadata)) {
+                && hasExactlyOneServicePort(serviceBuilder, serviceMetadata.getName())) {
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:106]: https://github.com/eclipse/jkube/pull/1447/files#r937814087

**Comment by rohanKanojia** [comment]
Looks good, Thanks! :+1:

**Review by manusa — APPROVED** [review]
