### PR TITLE
Fix #382: Add support for merging fragment Route spec with default generated Route

### LINKED ISSUE #382: Yaml extract for routes
### Description
The goal is to evolve a generated route with support for https. Adding something like to the spec:
```
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
```
It is not clear on how this should be handled. Currently custom spec element is not merged with the spec element of the generated route, the generated route's spec element is replaced with the content of the extract file. NB: this can be acceptable although the documentation doesn't state how to customize routes.

### Info

* Eclipse JKube version : 1.0.0

* If it's a bug, how to reproduce : add a route.yml extract in the src/jkube directory of a quickstart.

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #382 & #383 

RouteEnricher now considers merging opinionated route with route provided in resource fragments(if any). Earlier RouteEnricher used to skip a generation of the opinionated route if it found a route corresponding to target Service inside KubernetesListBuilder

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java [hunk 1]
```diff
@@ -727,6 +725,27 @@ private static void ensureHasPort(Container container, ContainerPort port) {
...
+        simpleFieldTypes.add(Short.class);
+        simpleFieldTypes.add(Character.class);
+        simpleFieldTypes.add(Byte.class);
+        simpleFieldTypes.add(double.class);
+        simpleFieldTypes.add(float.class);
+        simpleFieldTypes.add(long.class);
+        simpleFieldTypes.add(int.class);
+        simpleFieldTypes.add(short.class);
+        simpleFieldTypes.add(char.class);
+        simpleFieldTypes.add(byte.class);
```
Comment (manusa) [inline jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:744]: There are several things I don't understand here.
- Why did we replace the `Set` with an `ArrayList`?
- Why are we no longer statically initilizing the collection (The collection is now created each time we invoke the method)?
- If this collection is to be different depending on where it is invoked (e.g. DefaultControllerEnricher), why aren't we creating an instantiable dedicated util class where the Collection can be customized?

Comment (rohanKanojia) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:744]: This collection only seems to be getting used to distinguish whether a type is primitive or not. I don't think it's contents would vary depending upon the caller. I wanted to use it in RouteEnricher but I found out it's being initialized in DefaultControllerEnricher; which seemed weird to me.

Comment (rohanKanojia) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:744]: regarding replacing `Set` with `ArrayList` I think it's a mistake. Let me revert it to `Set`.

Comment (manusa) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java]: :+1: 
I'm still missing this _"Why are we no longer statically initializing the collection (The collection is now created each time we invoke the method)?"_

Comment (rohanKanojia) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java]: ohk, let me revert to static initialization inside KubernetesResourceUtil

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java [hunk 2]
```diff
@@ -983,16 +1002,24 @@ protected static void mergeMetadata(HasMetadata item1, HasMetadata item2) {
...
-            String value = entry.getValue();
-            if (value == null || value.isEmpty()) {
-                String key = entry.getKey();
-                answer.remove(key);
+        if (overrideMap == null && originalMap == null) {
+            return Collections.emptyMap();
+        } else if (originalMap == null) {
+            return overrideMap;
+        } else if (overrideMap == null) {
+            return originalMap;
```
Comment (manusa) [inline jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:1010]: MapUtil.mergeMaps already takes care of the initial checks you've done here
https://github.com/eclipse/jkube/blob/645268c18c1e43bad18cb146362cf253900904e3/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java#L59-L67

You probably just want to do this:
```java
final Map<String, String> answer = MapUtil.mergeMaps(overrideMap, originalMap);
if (overrideMap != null && originalMap != null) {
  /* ... */
}
return answer;
```

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java [hunk 3]
```diff
@@ -157,58 +151,111 @@ private boolean hasExactlyOneServicePort(ServiceBuilder service, String id) {
...
+    private void updateRouteDomainPostFixBasedOnServiceName(String serviceName) {
+        if (StringUtils.isNotBlank(routeDomainPostfix)) {
+            routeDomainPostfix = prepareHostForRoute(routeDomainPostfix, serviceName);
+        } else {
+            routeDomainPostfix = "";
+        }
+    }
+
+    static Route mergeRoute(Route routeFromFragment, Route opinionatedRoute) {
+        // Update ApiVersion to route.openshift.io/v1
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:185]: This comment is completely irrelevant.
If you want to add a helpful comment because it's necessary and cannot be inferred with a test, then write something like
`// Update version because of/due to....`

I read the code and still don't understand why the change in the api version is required. This comment only tells me what I can already read in the code.

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java [hunk 4]
```diff
@@ -157,58 +151,111 @@ private boolean hasExactlyOneServicePort(ServiceBuilder service, String id) {
...
+        if (routeFromFragment.getApiVersion().equals("v1")) {
+            routeFromFragment.setApiVersion(opinionatedRoute.getApiVersion());
+        }
+
+        // Merge metadata
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:190]: More irrelevant comments, I can read this in the code thanks to the helpful method name `mergeMetadata`
If you do an import static of the method, it will be even more obvious.

File: jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java [hunk 5]
```diff
@@ -171,6 +168,118 @@ public void testCreateWithDefaultsAndExistingRouteWithMatchingNameInBuilderInOpe
...
+                .editOrNewSpec()
+                .addNewPort()
+                .withName("http")
+                .withPort(8080)
+                .withProtocol("TCP")
+                .withTargetPort(new IntOrString(8080))
+                .endPort()
+                .addToSelector("group", "test")
+                .withType("LoadBalancer")
+                .endSpec();
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java:283]: If you preserve indentation. it's much easier to read.
Surround the code with `// @formatter:off` `// @formatter:on` comments so that autoformat won't accidentally break indentation.

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java (hunk 3 above)
Comment (manusa) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java:185]: https://github.com/eclipse/jkube/issues/383

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java (hunk 1 above)
Comment (manusa) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java]: I think this one still pending.

**Review by manusa — APPROVED** [review]

**Review by manusa — APPROVED** [review]
