### PR TITLE
fix (jkube-kit) : Add configuration option in ServiceAccountEnricher to skip creating ServiceAccounts (#1438)

### LINKED ISSUE #1438: Using a service account that already exists with openshift-maven-plugin and helm
### Info

* Eclipse JKube version : 1.7.0
* Maven version (`mvn -v`) : 3.8.1

Hi. I'm having some issues trying with the openshift-maven-plugin when it comes to trying to reference using a serviceAccount that already exists. If I add into the configuration section of the openshift-maven-plugin in my pom.xml (1.7.0) the following (as per the docs):

```xml
<build>
  <plugins>
    <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>openshift-maven-plugin</artifactId>
        <version>1.7.0</version>
        <configuration>
          <resources>
            <serviceAccount>a-service-account-that-exists</serviceAccount>
          </resources>
        </configuration>
    </plugin>
  </plugins>
</build>
```

and then in my src/main/jkube/deployment.yml snippet file I have:
```
metatdata:
  name: some-deployment
spec:
  template:
    spec:
      serviceAccountName: a-service-account-that-exists
```

If I run `mvn clean install oc:resource` on the project, I end up with a some-deployment-serviceaccount.yml file under target/classes/META-INF/jkube/openshift. However I would have expected no service account config to be created, as I just want to use a service account that already exists. Am I doing something wrong ?
We're trying to use jkube with helm (via oc:helm), but after creating the chart using `oc:resource oc:helm` and then trying to apply it, helm fails because the service account already exists and cannot be imported into the release due to differing metadata.
We basically want to use a service account that already exists and therefore not have the helm chart try and create it. 

Can somebody please advise?
Thanks

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #1438

Add Enricher configuration option `skipCreate` in ServiceAccountEnricher
to disable ServiceAccount creation.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [X] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ServiceAccountEnricher.java [hunk 1]
```diff
@@ -29,55 +32,77 @@
...
+        builder.addAllToServiceAccountItems(createServiceAccountFromResourceConfig(resourceConfig));
+        builder.addAllToServiceAccountItems(createServiceAccountsReferencedInDeployment(builder, deploymentToSaPair));
+    }
+
+    private List<ServiceAccount> createServiceAccountFromResourceConfig(ResourceConfig resourceConfig) {
+        List<ServiceAccount> serviceAccounts = new ArrayList<>();
+        if(resourceConfig != null && resourceConfig.getServiceAccounts() != null) {
+            for(ServiceAccountConfig serviceAccountConfig : resourceConfig.getServiceAccounts()) {
+                if(serviceAccountConfig.getName() != null
+                    && !Boolean.parseBoolean(getConfig(Config.SKIP_CREATE))) {
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ServiceAccountEnricher.java:73]: Checking for the skip create flag so late seems like a waste of resources. I'd either move this check to the calling method:
```java
if (!Boolean.parseBoolean(getConfig(Config.SKIP_CREATE)) {
 
 builder.addAllToServiceAccountItems(createServiceAccountFromResourceConfig(resourceConfig));
}
```

or to line 70 if clause

**Review by manusa — APPROVED** [review]
