### PR TITLE
Fix #671: ApplyMojo not considering namespace configured from XML configuration

### LINKED ISSUE #671: ApplyMojo not considering namespace configured from XML configuration
### Info
When I'm trying to do `k8s:apply` from a project where namespace is configured from XML rather than `jkube.namespace` property. I'm getting this error:
```
[INFO] k8s: Creating a ServiceAccount from kubernetes.yml namespace default name rokumar-serviceaccount
[ERROR] k8s: Failed to create ServiceAccount from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:rokumar. Operation namespace:default.. ServiceAccount(apiVersion=v1, automountServiceAccountToken=null, imagePullSecrets=[], kind=ServiceAccount, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=jkube-xml-resourceconfig, provider=jkube, version=1.0.0-SNAPSHOT, group=org.eclipse.jkube}, managedFields=[], name=rokumar-serviceaccount, namespace=rokumar, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), secrets=[], additionalProperties={}): io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:rokumar. Operation namespace:default.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
I think we're not considering namespace configured from ResourceConfig here:

https://github.com/eclipse/jkube/blob/3af6339ddfa16efbe42ef6e71687f583d74856ee/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java#L235-L239
* Eclipse JKube version : v1.2.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 11.0.9, vendor: Oracle Corporation, runtime: /usr/lib/java/jdk-11.0.9
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.14-200.fc33.x86_64", arch: "amd64", family: "unix"

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :
  - Clone the reproducer project
  - create a namespace `rokumar` or change namespace configured in pom to your desired namespace
  - `mvn k8s:resource k8s:apply`

* Sample Reproducer Project : https://github.com/r0haaaan/jkube-xml-resourceconfig/tree/namespace-bug

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #671 

Refactor ApplyService to consider namespace in resource metadata over the default namespace to enable applying resources in multiple namespaces
+ When no namespace is configured via XML or property, namespace gets picked from clusterAccess.getNamespace
+ When no namespace is configured via XML or property, but namespace is set in resource fragments, that particular namespace would be picked for those specific resources. Other resources would have clusterAccess.getNamespace namespace picked
+ When user provides namespace via `jkube.namespace` property. ALL resources are applied into namespace specified via `jkube.namespace`  property

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java [hunk 1]
```diff
@@ -82,19 +82,21 @@ private void undeployResources(String namespace, List<HasMetadata> entities) {
 
   protected Consumer<HasMetadata> resourceDeleter(String namespace) {
     return resource -> {
-      logger.info("Deleting resource %s %s/%s", KubernetesHelper.getKind(resource), namespace, KubernetesHelper.getName(resource));
+      String undeployNamespace = resolveEffectiveNamespace(resource, namespace);
```
Comment (manusa) [inline jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java:85]: Why isn't the namespace resolved after line 68 and passed on? (Just like we're doing now)

Comment (rohanKanojia) [reply jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java:85]: This is done to handle the case of multiple namespaces. In case resources have different namespaces in their metadata, it's given more precedence over standard namespace.

**Comment by rohanKanojia** [comment]
I have a doubt regarding this case:
> Non-generated or generated resources have namespace configured in fragment (this namespace may be different to that configured via XML ---> I have additional fragments/resources to deploy that don't belong to my application's domain). This specific, granular, per-resource configuration should take precedence over the more global XML configuration.

Once namespace is configured in XML like this:
```xml
<resources>
  <namespace>rokumar-stage</namespace>
</resources>
```
It will modify all resources' `metadata.namespace` field. How would our generated resources end up having different namespaces in this case? 

Shall we refactor DefaultNamespaceEnricher to only add namespace if not already present? We can add another flag (ex `jkube.namespace.forced`)  to override this behavior 
https://github.com/eclipse/jkube/blob/297b84661950cf8e1cab173919743967f02f1b55/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricher.java#L108

File: jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java [hunk 2]
```diff
@@ -362,6 +367,72 @@ public void testGetK8sListWithNamespaceFirstWithProject() {
...
+
+        // Then
+        collector.assertEventsRecordedInOrder("configmap-ns1-create", "serviceaccount-default-create", "ingress-ns2-create");
+        assertEquals(6, mockServer.getMockServer().getRequestCount());
+        applyService.setFallbackNamespace(null);
+        applyService.setNamespace(configuredNamespace);
+    }
+
+    @Test
+    public void testApplyToMultipleNamespacesOverriddenWhenNamespaceConfigured() throws InterruptedException {
```
Comment (manusa) [inline jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java:406]: I'm not sure what this test does compared to `testApplyToMultipleNamespaceNoNamespaceConfigured`

**Review by manusa — APPROVED** [review]
LGTM
