### PR TITLE
fix(jkube-kit) : Push goal doesn't skip push when image build skip field enabled (#1195)

### LINKED ISSUE #1195: kubernetes-maven-plugin - Skipped images still are pushed, which fails
### Description

As a dev I want to be able to skip the build and push of certain images based on property in my POM.

I can set up the build to skip certain images but it fails when being pushed as the images that were skipped do not exist. It should be possible to skip the deployment of specific images, via the same or a different configuration property.

Error:

> [ERROR] k8s: Error while trying to push the image: Unable to add tag [yyz.ocir.io/frxxxxxxxb/my-image:tf-014] to image [frxxxxxxxb/my-image:tf-014] : {"message":"No such image: frxxxxxxxb/my-image:tf-014"} (Not Found: 404) [Error while trying to push the image: Unable to add tag [yyz.ocir.io/frxxxxxxxb/my-image:tf-014] to image [frxxxxxxxb/my-image:tf-014] : {"message":"No such image: frxxxxxxxb/my-image:tf-014"} (Not Found: 404)]

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

Configuration is as so:

```xml
<plugin>
    <groupId>org.eclipse.jkube</groupId>
    <artifactId>kubernetes-maven-plugin</artifactId>
    <version>1.5.1</version>
    <executions>
        <execution>
            <id>docker-build</id>
            <phase>package</phase>
            <goals>
                <goal>build</goal>
            </goals>
        </execution>
        <execution>
            <id>docker-registry-push</id>
            <phase>deploy</phase>
            <goals>
                <goal>push</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <images>
            <image>
                <name>${dockerRepoPrefix}/%a:%v</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <tags>
                        <tag>latest</tag>
                    </tags>
                    <args>
                        <terraform_version>${dkr-terraform-version}</terraform_version>
                    </args>
                </build>
            </image>
            <image>
                <name>${dockerRepoPrefix}/%a:tf-014</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <skip>${skipTfVers}</skip>
                    <args>
                        <terraform_version>0.14.11</terraform_version>
                    </args>
                </build>
            </image>
            <image>
                <name>${dockerRepoPrefix}/%a:tf-013</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <skip>${skipTfVers}</skip>
                    <args>
                        <terraform_version>0.13.7</terraform_version>
                    </args>
                </build>
            </image>
            <image>
                <name>${dockerRepoPrefix}/%a:tf-012</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <skip>${skipTfVers}</skip>
                    <args>
                        <terraform_version>0.12.26</terraform_version>
                    </args>
                </build>
            </image>
        </images>
    </configuration>
</plugin>
```

#### Repro Steps

Run the above config with the following command:
`mvn deploy -D'skipTfVers=true'`

Note that the build phase correctly skips the indicated images with the particular TF versions, but it fails when the deploy is due to occur as (with a clear local reg) the images do not exist. I could find no way to specify `skipPush` at the image level (hopefully I have just missed that)

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1195

There is a skip field in BuildConfiguration class which skips image
build when enabled, but this doesn't work for push. Plugin tries to push
images even when they're not built and fails.

Handle skip field in RegistryService and JibBuildService

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/AbstractImageBuildService.java [hunk 1]
```diff
@@ -24,14 +27,30 @@ protected AbstractImageBuildService(JKubeServiceHub jKubeServiceHub) {
...
 
+  protected abstract void pushSingleImage(ImageConfiguration imageConfiguration, int retries, RegistryConfig registryConfig, boolean skipTag) throws JKubeServiceException;
+
   @Override
   public final void build(ImageConfiguration... imageConfigurations) throws JKubeServiceException {
+    processImage(this::buildSingleImage, "Skipped building", imageConfigurations);
+  }
+
+  @Override
+  public void push(Collection<ImageConfiguration> imageConfigs, int retries, RegistryConfig registryConfig, boolean skipTag) throws JKubeServiceException {
```
Comment (manusa) [inline jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/AbstractImageBuildService.java:38]: make this final

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+            .from("basefoo/basebar:0.1.0")
+            .tags(Arrays.asList("latest", "0.0.1-slim"))
+            .build())
+        .build();
+    registryService = new RegistryService(mockedDockerAccess, mockedLogger);
+    when(mockedRegistryConfig.getRegistry()).thenReturn("example.com");
+  }
+
+  @Test
+  public void pushImages_whenValidImageConfigurationProvidedWithSkipTag_shouldPushImages() throws IOException {
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java:72]: I understand that this is shouldNot instead of should, right?
```suggestion
  public void pushImages_whenValidImageConfigurationProvidedWithSkipTag_shouldNotPushImages() throws IOException {
```

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java [hunk 3]
```diff
@@ -0,0 +1,145 @@
...
+    // When
+    registryService.pushImage(imageConfiguration, 1, mockedRegistryConfig, true);
+
+    // Then
+    verify(mockedDockerAccess, times(1))
+        .pushImage(eq("foo/bar:0.0.1"), any(), eq("example.com"), anyInt());
+    verify(mockedDockerAccess, times(0))
+        .pushImage(eq("foo/bar:latest"), any(), eq("example.com"), anyInt());
+    verify(mockedDockerAccess, times(0))
+        .pushImage(eq("foo/bar:0.0.1-slim"), any(), eq("example.com"), anyInt());
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java:82]: I'm not following these test scenarios.

Why do we have 3 verifications?

methods should also be renamed to + `pushImage_...`

Comment (rohanKanojia) [reply jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java:82]: these three verifications are verifying all three tags are pushed. One specified in name and two specified in `<tags>`

Comment (manusa) [reply jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java:82]: OK, maybe a clearer expectation name can help

`pushImages_whenValidImageConfigurationProvidedWithSkipTag_shouldPushApplicableTags`

or

`pushImages_whenValidImageConfigurationProvidedWithSkipTag_shouldNotPushAdditionalTags`


And the opposite for the other test.

Comment (manusa) [reply jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java:82]: The other 2 verifications could be replaced by
```
verify(mockedDockerAccess, times(1))
    .pushImage(eq("foo/bar:0.0.1"), any(), eq("example.com"), anyInt());
verify(mockedDockerAccess, times(1))
        .pushImage(any(), any(), any(), anyInt());
```

Which makes the test more reliable (you verify that nothing else, despite the name, is pushed)

**Review by manusa — APPROVED** [review]

**Review by sunix — APPROVED** [review]
