### PR TITLE
fix : `jkube.enricher.jkube-name.name` doesn't modify `.metadata.name` for generated manifests (#1325)

### LINKED ISSUE #1325: `jkube.enricher.jkube-name.name` doesn't modify `.metadata.name` for generated manifests
### Description

I noticed this while writing a test for https://github.com/eclipse/jkube/issues/1259 . What I'm observing is that generated resources always seem to have default opinionated name whether we provide `jkube.enricher.jkube-name.name` flag or not.

NameEnricher seems to be working okay as a single unit. I think the problem lies in the ordering of this enricher:

https://github.com/eclipse/jkube/blob/9568ece851fe2a4b6c6d9814053b2f292679aa8d/gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml#L24-L28

We use name enricher right at the beginning. In zero configuration setting there is no resource available at this time. DefaultControllerEnricher and DefaultServiceEnricher kick in later to generate/customize Deployment/Services. 

We should move it to the bottom so that name can be changed after all manifests have been generated.

### Info

* Eclipse JKube version : 1.7.0

* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce : Try doing `mvn k8s:resource -Djkube.enricher.jkube-name.name=somename`, generated manifests won't have `.metadata.name` set to `somename`

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1325 

Change ordering of NameEnricher and modify it's logic to override name in
case of custom enricher configuration

Signed-off-by: Rohan Kumar <rohaan@redhat.com>
## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/1326 (_2022-03-07T14:16:36Z_)

:gear: [JKube E2E Tests (1945946539)](https://github.com/jkubeio/ci/actions/runs/1945946539) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#1326)](https://github.com/jkubeio/ci/runs/5449596550?check_suite_focus=true)

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java [hunk 1]
```diff
@@ -48,11 +48,14 @@ public NameEnricher(JKubeEnricherContext buildContext) {
 
   @Override
   public void create(PlatformMode platformMode, KubernetesListBuilder builder) {
-    final String defaultName = getConfig(Config.NAME, JKubeProjectUtil.createDefaultResourceName(getContext().getGav().getSanitizedArtifactId()));
+    final String configuredName = getConfig(Config.NAME);
+    final String defaultName = JKubeProjectUtil.createDefaultResourceName(getContext().getGav().getSanitizedArtifactId());
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java:52]: Why is this change necessary, isn't the getConfig(key, defaultValue) taking care of this?

**Comment by manusa** [comment]
> Change ordering of NameEnricher and modify it's logic to override name in
case of custom enricher configuration

We need to provide a test that makes sure of this. Else we can reorder enrichers in the future again and revert these changes. (Consider we recently reordered the profiles for healthcheck enrichers, imagine that this reordering broke this feature. Now we could be inadvertently reverting that change)

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java (hunk 1 above)
Comment (rohanKanojia) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java:52]: I wanted NameEnricher's `Config.NAME` configuration option to take precedence over currently configured name in resource. Resource `.metadata.name` is overwritten if `Config.Name` is non blank regardless of it's value. However, `.metadata.name` is only overwritten in the default case if its value is `null`/empty.

Comment (manusa) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java:52]: OK, the current structure makes it very confusing to read.
So the idea is that the precedence is:
- getConfig(Config.NAME) ---> create_withCustomNameAndAlreadyExistingName_shouldOverrideExistingName
- resource.getName() ----> *1
- JKubeProjectUtil.createDefaultResourceName(getContext().getGav().getSanitizedArtifactId()) ----> *2

Are there tests for 1 & 2?

**Review by sunix — APPROVED** [review]

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java (hunk 1 above)
Comment (rohanKanojia) [reply jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java:52]: I think you're right. for 2 there seems to be `createWithDefaultsInKubernetes` test which verifies opinionated name use case.

For 1, I'm going to add a test case

File: jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/NameEnricherTest.java [hunk 2]
```diff
@@ -105,4 +102,49 @@ public boolean matches(Object value) {
...
+      public boolean matches(Object value) {
+        return value != null;
+      }
+    };
+    assertThat(klb.build().getItems())
+        .hasSize(1)
+        .extracting(HasMetadata::getMetadata)
+        .filteredOn(nonNull)
+        .extracting(ObjectMeta::getName)
+        .containsExactly("existing-name");
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/NameEnricherTest.java:125]: I think that what you probably want is 

assertThat(klb.build().getItems()).singleElement().extracting(HasMetadata::getMetadata).extracting(ObjectMeta::getName).isEqualTo()

or 

assertThat(klb.build().getItems()).singleElement().extracting("metadata.name").isEqualTo("existing-name")

or

assertThat(klb.build().getItems()).singleElement().hasFieldOrPropertyWithValue("metadata.name", "existing-name");

?

**Review by manusa — APPROVED** [review]
