### PR TITLE
Fix #887: Incorrect warning about overriding environment variable

### LINKED ISSUE #887: Incorrect warning about overriding environment variable
### Info

* Eclipse JKube version : 1.4.0
* Maven version (`mvn -v`) :
```
Maven home: /usr/share/maven
Java version: 11.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.fc34.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.12-200.fc34.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version : k8s 1.21

* If it's a bug, how to reproduce : Just adding images with environment vars that can be overriden to resources. Ex.
````
<configuration>
	<images>
		<image>
			<name>quay.io/example/%a:%l</name>
			<build>
				<from>quay.io/jkube/jkube-java-binary-s2i:0.0.9</from>
				<assembly>
					<targetDir>/deployments</targetDir>
				</assembly>
			</build>
		</image>
	</images>
	<resources>
		<env>
			<!-- disable jolokia -->
			<AB_JOLOKIA_OFF>true</AB_JOLOKIA_OFF>
			<JAVA_OPTIONS>-Djgroups.dns.query=${project.artifactId}-ping</JAVA_OPTIONS>
			<JAVA_ARGS>--spring.profiles.active=${deployment.mode},${infinispan.mode} --spring.application.name=customer-service-cache --spring.cloud.kubernetes.config.name=customer-service-cache-config --spring.cloud.kuberentes.config.paths=/opt/jboss/etc --spring.cloud.kubernetes.config.enableApi=false</JAVA_ARGS>
		</env>
	</resources>
</configuration>
````

* Log:
```
[INFO] k8s: jkube-controller: Adding a default Deployment
[WARNING] k8s: jkube-image: Environment variable AB_JOLOKIA_OFF will not be overridden: trying to set the value true, but its actual value is true
[WARNING] k8s: jkube-image: Environment variable JAVA_ARGS will not be overridden: trying to set the value --spring.profiles.active=kubernetes,embedded --spring.application.name=customer-service-cache --spring.cloud.kubernetes.config.name=customer-service-cache-config --spring.cloud.kuberentes.config.paths=/opt/jboss/etc --spring.cloud.kubernetes.config.enableApi=false, but its actual value is --spring.profiles.active=kubernetes,embedded --spring.application.name=customer-service-cache --spring.cloud.kubernetes.config.name=customer-service-cache-config --spring.cloud.kuberentes.config.paths=/opt/jboss/etc --spring.cloud.kubernetes.config.enableApi=false
[WARNING] k8s: jkube-image: Environment variable JAVA_OPTIONS will not be overridden: trying to set the value -Djgroups.dns.query=customer-service-cache-ping, but its actual value is -Djgroups.dns.query=customer-service-cache-ping
```

* Sample Reproducer Project : https://github.com/rgordill/customer-service-cache

* Other references: It is also shown in this blog: https://www.wildfly.org/news/2021/02/01/Bootable-jar-jkube-clustering-openshift/

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #887
Don't log a warning about not overriding environment variable when both
old and new values are same.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ImageEnricher.java [hunk 1]
```diff
@@ -83,7 +83,7 @@ public ImageEnricher(JKubeEnricherContext buildContext) {
         PULL_POLICY("pullPolicy");
 
         @Getter
-        protected String key;
+        private String key;
```
Comment (manusa) [inline jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ImageEnricher.java:86]: I'm not sure if this might affect deserialization at some point. Let's just not modify this in this PR.
We can reevaluate and change the rest of Configs.Config accordingly (all of them declare the fields as protected)

**Review by manusa — APPROVED** [review]
