### PR TITLE
fix: Watch uses same logic as build to monitor changed assembly files

### LINKED ISSUE #238: WatchService doesn't consider changes FileSet assemblies
## Description

WatchMojo still doesn't work for more complex Assemblies where assembled files for the Image come from different sources.

## How to reproduce
Trying watch goal in [OpenLiberty](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/openliberty) quickstart won't work OK because some of the required assembly files won't be copied over to the Docker image.

Relates to #234

### PR DESCRIPTION
**Pull request by manusa**
## Description
Watch uses same logic as build to monitor changed assembly files (fixes #238 )

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [ ] ~I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly~
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
   - One new code smell reported for TODO related to #94 for AssemblyFile permission/fileMode
 - [x] I tested my code in Kubernetes
 - [ ] ~I tested my code in OpenShift~

### CODE REVIEW

File: jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java [hunk 1]
```diff
@@ -391,6 +357,8 @@ private void processJKubeProjectAssemblyFile(
         final String destinationFilename = Optional.ofNullable(assemblyFile.getDestName()).orElse(sourceFile.getName());
         final File destinationFile = new File(outputDirectory, destinationFilename);
         FileUtil.copy(sourceFile, destinationFile);
+        // TODO: Need to add permission (Probably change AssemblyFile model to have this)
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java:360]: Should we file a separate issue for this pending task? Wdyt?

Comment (manusa) [reply jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java:360]: See PR description in point "No new bugs, code smells...". Everything already linked up (I don't really like leaving ToDos in code, but this one was already quite big without further changes, and I already left the placeholder for the future fix)

Comment (rohanKanojia) [reply jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java:360]: Ah, sorry. Looks like I didn't see linked issue in description
