### PR TITLE
fix : Throw Exception when podman daemon returns `null` for image id post build(#1055)

### LINKED ISSUE #1055: Building a new image from a detected Dockerfile and podman is showing: `Built image null`
### Description

Building a new image from a detected Dockerfile and podman is showing: Built image null
```
[INFO] --- kubernetes-maven-plugin:1.4.0:build (default-cli) @ live-stream-question ---
[INFO] k8s: Running in Kubernetes mode
[INFO] k8s: Building Docker image in Kubernetes mode
[INFO] k8s: [java/live-stream-question:1.0.0]: Created docker-build.tar in 547 milliseconds
[INFO] k8s: [java/live-stream-question:1.0.0]: Built image null
```
### Info

* Eclipse JKube version : 1.4.0
* Maven version (`mvn -v`) : 3.6.3

* Kubernetes / Red Hat OpenShift setup and version :
podman version 3.2.3

* If it's a bug, how to reproduce :

1. `git clone https://github.com/parisjug/live-stream-question.git`
2. Configure podman and start podman rest api:
  ```
export DOCKER_HOST="unix:/run/user/$(id -u)/podman/podman.sock"
podman system service --time=0 unix:/run/user/$(id -u)/podman/podman.sock &
```
3. Add the Jkube build plugin to the pom.xml
   ```
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>1.4.0</version>
      </plugin>
   ```
4. Run the build `mvn package k8s:build`
Selection_543

The project contains a Dockerfile in the root folder of the repo.

* Sample Reproducer Project : *https://github.com/parisjug/live-stream-question.git*

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #1055

Right now podman daemon doesn't fail the build sometimes when it's not
able to build image sucessfully. In case of #1055, image was being built
but when plugin tries to fet image id of the corresponding built image,
podman fails to resolve it and therefore `null` message is printed.

Add a null check when image id isn't resolved and throw an
IllegalStateException instead.

So instead of logging this:
```
[INFO] k8s: [java/live-stream-question:1.0.0]: Built image null
```
we should see this exception being thrown:
```
[ERROR] k8s: Failed to execute the build [Failure in building image, unable to find image built with name java/live-stream-question:1.0.0]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.229 s
[INFO] Finished at: 2022-01-20T22:41:07+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.6.0-SNAPSHOT:build (default-cli) on project live-stream-question: Failed to execute the build: Failure in building image, unable to find image built with name java/live-stream-question:1.0.0 -> [Help 1]
```

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java [hunk 1]
```diff
@@ -13,78 +13,76 @@
...
+  private BuildService mockedDockerBuildService;
 
-  @Test
-  public void build_withValidConfiguration_shouldBuildAndTag() throws Exception {
-    // Given
-    final ImageConfiguration image = ImageConfiguration.builder()
+  @Before
+  public void setUp() {
+    mockedJKubeServiceHub = mock(JKubeServiceHub.class, RETURNS_DEEP_STUBS);
+    mockedDockerBuildService = mock(BuildService.class, RETURNS_DEEP_STUBS);
```
Comment (sunix) [inline jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java:48]: I think it's more readable if you skip these lines and 
- add `@Mock(answer = Answers.RETURNS_DEEP_STUBS)` to the 2 attributes
- use runner `@RunWith(MockitoJUnitRunner.class)`

WDYT ?

**Review by sunix — APPROVED** [review]
LGTM, added a suggestion but it is up to you.

File: jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java (hunk 1 above)
Comment (rohanKanojia) [reply jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java:48]: okay, let me update this as per your suggestion.

**Review by manusa — APPROVED** [review]
