### PR TITLE
Fix #908: OpenShift-Maven-Plugin doesn't remove periods from opinionated container name

### LINKED ISSUE #908: OpenShift Maven Plugin doesn't remove periods from container name.
### Description

I noticed this when I was trying to reproduce https://github.com/eclipse/jkube/issues/904. If you go to [quickstarts/maven/quarkus-customized-image](https://github.com/eclipse/jkube/tree/5e8b297a379cbe13745574a34440e3c0bcfa291c/quickstarts/maven/quarkus-customized-image), image name is configured like this:
```xml
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>openshift-maven-plugin</artifactId>
        <version>${jkube.version}</version>
        <configuration>
          <images>
            <image>
              <name>${project.groupId}/${project.artifactId}</name>
```

If you'll do `oc:resource` you get a warning at validation phase regarding invalid container name:
```
[WARNING] oc: Invalid Resource : /home/rokumar/work/repos/jkube/quickstarts/maven/quarkus-customized-image/target/classes/META-INF/jkube/openshift/quarkus-customized-image-deploymentconfig.yml
[message=.spec.template.spec.containers[0].name: does not match the regex pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$, violation type=pattern]
```
If you go ahead and do `mvn oc:apply`, the process is going to fail and you'll get 422 from Kubernetes API server.

JKube seems to be generating this as container name:
```yaml
          image: org.eclipse.jkube.quickstarts.maven/quarkus-customized-image:latest
          imagePullPolicy: IfNotPresent
          name: org.eclipse.jkube.quickstarts.maven-quarkus-customized-image
```

I tried same project with fabric8 maven plugin v4.4.1 and it seems to be working okay. Fabric8 Maven Plugin seems to be generating this as container name(notice all periods in container name are removed):
```yaml
          image: org.eclipse.jkube.quickstarts.maven/quarkus-customized-image:latest
          imagePullPolicy: IfNotPresent
          name: orgeclipsejkubequickstartsmaven-quarkus-customized-image
```

### Info

* Eclipse JKube version : 1.4.0

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #908 
In quickstarts/maven/quarkus-customized-image,
KubernetesResourceUtil.extractContainerName tries to create an
opinionated container name from image name, but  in case image user also
contains periods, it doesn't sanitize it.

Add a replaceAll statement to sanitize returned imageUser.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java [hunk 1]
```diff
@@ -399,7 +399,7 @@ private static String extractImageUser(String image, String groupId) {
         String imageUser = name.getUser();
         String projectGroupId = groupId;
         if(imageUser != null) {
-            return imageUser;
+            return imageUser.replaceAll("[^a-zA-Z0-9-]", "");
```
Comment (manusa) [inline jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:402]: Was this ported from FMP?

Comment (rohanKanojia) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:402]: No, in FMP imageUser comes off as `null`. This is just taken from line 408(https://github.com/eclipse/jkube/issues/908#issuecomment-919123278)

Comment (manusa) [reply jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java:402]: https://github.com/fabric8io/fabric8-maven-plugin/blob/6525f61c042ebacfe7c945f9d8361598a5c95e31/core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java#L417

**Review by manusa — APPROVED** [review]
