### PR TITLE
fix: Debug goals work with QuarkusGenerator generated container images

### LINKED ISSUE #473: Support debug on Quarkus (k8s:debug / oc:debug)
## Description

[QuarkusGenerator](https://github.com/eclipse/jkube/blob/db9c522bce061f4e327c4e9f06930b5ac29b70b2/jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java) is based on [BaseGenerator](https://github.com/eclipse/jkube/blob/db9c522bce061f4e327c4e9f06930b5ac29b70b2/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java) and provides a specific [ENTRYPOINT](https://github.com/eclipse/jkube/blob/db9c522bce061f4e327c4e9f06930b5ac29b70b2/jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java#L101) for container startup.

This means that setting the `JAVA_ENABLE_DEBUG` even if the base image is the standard for JavaExecGenerator, debug startup is prevented since the standard entrypoint is overridden.

In order to unify Generators logic, QuarkusGenerator should extend from JavaExecGenerator. In addition, entrypoint should be respected, and only overridden for Native mode.

### PR DESCRIPTION
**Pull request by manusa**
## Description

fix #473: Debug goals work with QuarkusGenerator generated container images

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [ ] ~~I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly~~
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Failing Quarkus tests are related to the number of exposed ports in the generated images.
The change in this PR enables now both the Jolokia and Prometheus agent Ports.
I'll change E2E tests after merging this PR.

File: jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java [hunk 1]
```diff
@@ -13,163 +13,175 @@
...
+import org.apache.commons.lang3.StringUtils;
+
+public class QuarkusGenerator extends JavaExecGenerator {
+
+  public QuarkusGenerator(GeneratorContext context) {
+    super(context, "quarkus");
+  }
+
+  @AllArgsConstructor
+  public enum Config implements Configs.Config {
```
Comment (rohanKanojia) [inline jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java:47]: Is `WEB_PORT` Config parameter dropped intentionally?

**Review by rohanKanojia — APPROVED** [review]
