### PR TITLE
Modified outputDirectory in watchContext.buildContext

### LINKED ISSUE #2640: Fix `jkube-kit/build/service` module's unit tests on Windows
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

_Originally posted by @l3002 in https://github.com/eclipse/jkube/issues/2629#issuecomment-1933484184_

> a few tests are still failing in `jkube-kit/build/service` module. Here's a screenshot for your reference

When running `mvn clean install` on Windows, I see the following tests failing in `jkube-kit/build/service` module:

- [WatchServiceTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java)

TODO: Figure out what's not working as expected and propose a way to fix this

Screenshot 2024-02-08 124307

### PR DESCRIPTION
**Pull request by l3002**
## Description

Fixes #2640 

Modified the property `outputDirectory` in `WatchContext.buildContext` to return Relative Path rather than the Absolute Path.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2678 (_2024-02-15T19:22:58Z_)

:gear: [JKube E2E Tests (7921196563)](https://github.com/jkubeio/ci/actions/runs/7921196563) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2678)](https://github.com/jkubeio/ci/actions/runs/7921196563/job/21625945734)

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java [hunk 1]
```diff
@@ -94,7 +94,7 @@ void setUp(@TempDir Path tempDir) throws IOException {
         .project(JavaProject.builder()
           .baseDirectory(tempDir.toFile())
           .build())
-        .outputDirectory(Files.createDirectory(tempDir.resolve("target")).toFile().getAbsolutePath())
+        .outputDirectory(Files.createDirectory(tempDir.resolve("target")).toFile().getName())
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java:97]: Looks good.
However, for clarity, we might want to create the target directory in a variable outside the builder and then just reference it here.

```java
Files.createDirectory(tempDir.resolve("target"));
// suggested changes
```
```suggestion
        .outputDirectory("target")
```

**Review by rohanKanojia — APPROVED** [review]

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java [hunk 2]
```diff
@@ -89,12 +89,13 @@ void setUp(@TempDir Path tempDir) throws IOException {
...
         .build())
       .build();
+    Path path = Files.createDirectory(tempDir.resolve("target"));
     watchContext = WatchContext.builder()
       .buildContext(JKubeConfiguration.builder()
         .project(JavaProject.builder()
           .baseDirectory(tempDir.toFile())
           .build())
-        .outputDirectory(Files.createDirectory(tempDir.resolve("target")).toFile().getAbsolutePath())
+        .outputDirectory(path.toFile().getName())
```
Comment (manusa) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java:98]: As stated previously, for clarity, it would be better if this read as a string literal:
```suggestion
        .outputDirectory("target")
```

It's less confusing, and we understand that the value intended to go here is the name of the output directory which in this case is `target`

Comment (l3002) [reply jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java:98]: Oh, I'm sorry, I thought you meant to say that I need to make it more readable by separating creation from assignation. No problem, I'll get to it.

Comment (manusa) [reply jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java]: awesome, thx
