### PR TITLE
fix(helm): skip flag does not work for helm tasks

### LINKED ISSUE #3820: Maven Multi-Module Project - Skip flag does not work for helm tasks.
### Describe the bug

When using the jkube plugin in a multi-module project with the following structure:
 - Top Level, parent pom, defines the jkube plugin in plugin management
 - Child project - defines project and creates container and helm charts
 - Child project - defines integration tests

When building the project using (at the top level):

mvn clean install k8s:resource ks8:build k8s:helm k8s:helm-push

The following error is received:

`[INFO] 
[INFO] --- k8s:1.18.2:resource (default-cli) @ apprestws-parent ---
[INFO] k8s: `k8s:resource` goal is skipped.
[INFO] 
[INFO] --- k8s:1.18.2:build (default-cli) @ apprestws-parent ---
[INFO] k8s: `k8s:build` goal is skipped.
[INFO] 
[INFO] --- k8s:1.18.2:helm (default-cli) @ apprestws-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Test Project Parent 1.0-SNAPSHOT:
[INFO] 
[INFO] Test Project - Parent .............................. FAILURE [  3.067 s]
[INFO] Test Project - Spring Boot ......................... SKIPPED
[INFO] Test Project - Integration Tests ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.556 s
`

Maven version: 3.9.10
Java Version: 17.0.17
Build env: RedHat 8

### Eclipse JKube version

1.18.2

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

See attached maven project tar file.

In parent directory, run:

mvn clean install k8s:resource k8s:helm

A sample project that demonatrates this against 1.18.2 is: https://github.com/alehane/jkube-skip-test-project

### Expected behavior

K8s tasks should be skipped on parent project

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Linux

### Eclipse JKube Logs

```shell

```

### Sample Reproducer Project

https://github.com/alehane/jkube-skip-test-project

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ash-thakur-rh**
## Description
Fixes #3820 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java [hunk 1]
```diff
@@ -69,17 +69,17 @@ protected AbstractJKubeTask(Class<? extends KubernetesExtension> extensionClass)
 
   @TaskAction
   public final void runTask() {
-    init();
+    kubernetesExtension.javaProject = GradleUtil.convertGradleProject(getProject());
```
Comment (ash-thakur-rh) [inline gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java]: Initialization of gradle project is required before creating logger as logger is using gradle logger, which is not the case with maven Mojo. Missing initialization was creating issue in gradle plugin's tasks.

File: gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java [hunk 2]
```diff
@@ -109,7 +107,7 @@ public Property<Boolean> getSkipPush() {
 
     // Then
     assertThat(dockerBuildServiceMockedConstruction.constructed()).isEmpty();
-    verify(pushTask.jKubeServiceHub.getBuildService(), times(0)).push(any(), anyInt(), anyBoolean());
+    assertThat(pushTask.jKubeServiceHub).isNull();
```
Comment (manusa) [inline gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java]: This change should not be neessary

File: kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/SkipGoalsTest.java [hunk 3]
```diff
@@ -22,10 +23,7 @@
 import org.mockito.Mock;
 import org.mockito.Spy;
 
-import static org.mockito.Mockito.doNothing;
-import static org.mockito.Mockito.never;
-import static org.mockito.Mockito.verify;
-import static org.mockito.Mockito.when;
+import static org.mockito.Mockito.*;
```
Comment (manusa) [inline kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/SkipGoalsTest.java]: we don't use wildcard imports

**Review by manusa — CHANGES_REQUESTED** [review]

File: openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftUndeployMojoTest.java [hunk 4]
```diff
@@ -75,5 +94,28 @@ void getRuntimeMode() {
...
+      project = mockProject;
+      settings = OpenshiftUndeployMojoTest.this.settings;
+      skipUndeploy = true;
+      mojoExecution = mockExecution;
+    }};
+    // When
+    skipUndeployMojo.execute();
+    // Then
+    // No exception should be thrown, and no undeploy should happen
+    assertThat(skipUndeployMojo.skipUndeploy).isTrue();
```
Comment (manusa) [inline openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftUndeployMojoTest.java]: This one doesn't look good, it's basically asserting what you set in line 111
