### PR TITLE
Fix #639: Configuring Quotas for OpenShift BuildConfig not working as expected

### LINKED ISSUE #639: Quotas for jkube.build.strategy docker
### Info

* Eclipse JKube version : 1.1.1
* Maven version (`mvn -v`) : 3.6.1
* Kubernetes / Red Hat OpenShift setup and version : Openshift 4.6

Hello,

I switched from fabric8-maven-plugin to openshift-maven-plugin. The most things are working good.
But I can't find how to handle quotas for local docker builds.

I use this build strategy `<jkube.build.strategy>docker</jkube.build.strategy>`.
In fabric8 I defined quotas like this:
```
<openshiftBuildConfig>
	<requests>
		<cpu>${request_cpu_build}</cpu>
		<memory>${request_memory_build}</memory>
	</requests>
	<limits>
		<cpu>${limit_cpu_build}</cpu>
		<memory>${limit_memory_build}</memory>
	</limits>
</openshiftBuildConfig>
```
In the documentation this section vanished and I don't know how to handle quotas now. How am I supposed to define this?
Thanks in advance.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #639 

+ Fixed OpenShift BuildConfig not getting picked up bug
+ Add documentation for XML resource configuration options

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [X] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

File: kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojoTest.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        // Given
+        BuildMojo buildMojo = new BuildMojo() { {
+            project = mavenProject;
+            resources = ResourceConfig.builder()
+                    .openshiftBuildConfig(OpenshiftBuildConfig.builder()
+                            .limit("cpu", "200m")
+                            .request("memory", "1Gi")
+                            .build())
+                    .build();
+        }};
```
Comment (manusa) [inline kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojoTest.java:51]: You're overriding a tested class and then testing it. This is not OK.
If you need access to a particular member field only accessible through injection, make it protected or package private instead (in fact, I think both these fields are already accessible).

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc [hunk 2]
```diff
@@ -121,9 +121,14 @@ include::enricher/_jkube_service.adoc[]
 [[jkube-image]]
 ==== jkube-image
 
+include::enricher/_jkube_ingress.adoc[]
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc:124]: Entry summary should be added to `Table 41. Default Enrichers Overview`

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc [hunk 3]
```diff
@@ -121,9 +121,14 @@ include::enricher/_jkube_service.adoc[]
...
+
 [[jkube-name]]
 ==== jkube-name
 
+[[jkube-metadata]]
+include::enricher/_jkube-metadata.adoc[]
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc:130]: Entry summary should be added to `Table 41. Default Enrichers Overview` 

Entries are sorted alphabetically, this one should go before `jkube-name`

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc [hunk 4]
```diff
@@ -156,8 +161,9 @@ include::enricher/_jkube_triggers_annotation.adoc[]
 
 include::enricher/_jkube_secret_file.adoc[]
 
-[[jkube-serviceaccount]]
-==== jkube-serviceaccount
+include::enricher/_jkube_docker-registry-secret.adoc[]
+
+include::enricher/_jkube_serviceaccount.adoc
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc:166]: Entry summary link in `Table 41. Default Enrichers Overview`  should be fixed

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube-metadata.adoc [hunk 5]
```diff
@@ -0,0 +1,47 @@
+[[jkube-metadata]]
+===== jkube-metadata
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube-metadata.adoc:2]: This should be an H4
```suggestion
==== jkube-metadata
```

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube-metadata.adoc [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+|===
+
+[[metadata-xml-configuration]]
+===== Labels/Annotations XML Configuration
+Here are the supported options while providing `<labels>` or `<annotations>` in XML configuration
+
+.XML metadata configuration `<labels>`/`annotations>`
+[cols="1,5"]
+|===
+| Element | Description
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube-metadata.adoc:28]: The new serviceAccount is missing in this table

**Comment by manusa** [comment]
Relates to #551

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc [hunk 7]
```diff
@@ -116,17 +125,33 @@ include::enricher/_jkube_container_env_java_options.adoc[]
...
+include::enricher/_jkube_docker-registry-secret.adoc[]
+
+include::enricher/_jkube_git.adoc[]
 
 [[jkube-image]]
 ==== jkube-image
 
+include::enricher/_jkube_ingress.adoc[]
+
+[[jkube-metadata]]
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc:140]: This seems to be duplicate, I think it can be removed (it's already in the include file)

File: kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_docker-registry-secret.adoc [hunk 8]
```diff
@@ -0,0 +1,31 @@
+[[jkube-docker-registry-secret]]
```
Comment (manusa) [inline kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_docker-registry-secret.adoc:1]: The content of this is duplicate to the one in section `5.1.2 Secrets`

The Enricher entry is maybe valid in order to show how to activate or de-activate this feature when using profiles. But duplicating content will mislead users + be harder to maintain, just point/link to the right section of the documentation.

Something like:
`This enricher enables the {goal-prefix}:resource Secret feature.`, `You can read more about this feature here.`...

**Review by manusa — APPROVED** [review]
LGTM, thx!
