### PR TITLE
Fix #624: Unable to override Image Name in Simple Dockerfile Mode with `jkube.generator.name`

### LINKED ISSUE #624: Not able to override Image Name in Simple Dockerfile Mode with `jkube.generator.name`
When using simple Dockerfile mode, we're not able to override the default image name using `jkube.generator.name` property. Seems like we always assume image name to be group:artifact:latest in zero dockerfile mode and don't consider whether `jkube.generator.name` property is set or not, we do pass a defaultImageName but somehow it seems to be passed as null:

https://github.com/eclipse/jkube/blob/fd9003cf04fd2bcd7407e87ffc30dbf41d8a24b7/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java#L249-L252

In order to reproduce this, you can go to quickstarts/maven/docker-file-simple and try overriding image name by adding some property. I noticed this when testing @ghassen1khalil sample: https://github.com/ghassen1khalil/jkube-error-reproducer

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #624 
Modify Mojos logic to consider image name configured from properties

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
I think I removed usage of properties in DockerFileUtil. Now properties needed for defaultImageName are resolved in Mojos and resolvedImageName is passed to DockerFileUtil

File: jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java [hunk 1]
```diff
@@ -39,4 +39,20 @@ public static Properties getPropertiesFromResource(URL resource) {
...
   }
+
+  /**
+   * Return first Non Null set property from a set of provided properties
+   *
+   * @param properties {@link Properties} in a given project
+   * @param keys an array of property key values to find
+   * @return a string which is first non null value found for the provided list
+   */
+  public static String getValueFromProperties(Properties properties, String[] keys) {
```
Comment (manusa) [inline jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java:50]: Changing to:
```suggestion
  public static String getValueFromProperties(Properties properties, String... keys) {
```
will make life easier for method users and invocations will look clearer.

File: jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java [hunk 2]
```diff
@@ -39,4 +39,20 @@ public static Properties getPropertiesFromResource(URL resource) {
...
+    for (String property : keys) {
+      if (properties.containsKey(property)) {
+        return properties.get(property).toString();
```
Comment (manusa) [inline jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java:53]: It might make sense to check if the property is not blank either

(get property, check if not null, check if not blank, return)

**Review by manusa — CHANGES_REQUESTED** [review]
see comment

**Review by manusa — APPROVED** [review]

**Review by manusa — APPROVED** [review]
